import type { FormDoc } from "./types";

/**
 * ທະບຽນແບບຟອມ ແລະ ເອກະສານ (Form Register) — ທຸກເອກະສານທີ່ໃຊ້ ຫຼື ເກີດຂຶ້ນ
 * ໃນຂະບວນການສາງ ພ້ອມ: ໃຜເປັນເຈົ້າຂອງ · ເກີດຢູ່ໜ້າໃດ · ໃຊ້ເມື່ອໃດ · ເກັບດົນປານໃດ.
 */
export const FORMS: FormDoc[] = [
  {
    code: "F-01",
    name: "ໃບ packing (ນຳເຂົ້າ)",
    kind: "Excel",
    docNo: "PK<ປປດດວວ>-#####",
    source: { label: "ຮັບສິນຄ້າ › ໃບ packing", href: "/movements/receive" },
    owner: "receiver",
    when: "ເມື່ອສິນຄ້າມາຮອດ ກ່ອນສ້າງໃບກວດນັບ",
    fields: ["ຜູ້ສະໜອງ", "PO ອ້າງອີງ", "ລາຍການ + ຈຳນວນ", "ໄຟລ໌ PDF ແນບ"],
    retention: "3 ປີ (ໄຟລ໌ໃນລະບົບ)",
    sops: ["SOP-WH-01"],
  },
  {
    code: "F-02",
    name: "ໃບສັ່ງຊື້ (PO)",
    kind: "ERP",
    source: { label: "ລາຍການຄ້າງຮັບ", href: "/movements/receive?tab=pending" },
    owner: "purchasing",
    when: "ກ່ອນສິນຄ້າມາຮອດ — ຕ້ອງອະນຸມັດແລ້ວ",
    fields: ["ຜູ້ສະໜອງ", "ລາຍການ + ຈຳນວນ + ລາຄາ", "ສະຖານະອະນຸມັດ", "ສາງປາຍທາງ"],
    retention: "ຕາມລະບຽບ ERP",
    sops: ["SOP-WH-01"],
  },
  {
    code: "F-03",
    name: "ໃບກວດນັບຮັບເຂົ້າ",
    kind: "ລະບົບ",
    docNo: "CK<ປປດດວວ>-#####",
    source: { label: "ຮັບສິນຄ້າ › ໃບກວດນັບ", href: "/movements/receive?tab=count" },
    owner: "receiver",
    when: "ຂະນະນັບສິນຄ້າທີ່ຮັບ (1 ໃບ ອ້າງໄດ້ຫຼາຍ PO ແຕ່ສາງດຽວ)",
    fields: ["PO ທີ່ອ້າງ", "ລາຍການ + ຈຳນວນນັບ", "ISN", "ຜູ້ນັບ", "ໝາຍເຫດ"],
    retention: "3 ປີ",
    sops: ["SOP-WH-01"],
  },
  {
    code: "F-04",
    name: "ໃບຮັບສິນຄ້າເຂົ້າ WMS",
    kind: "ລະບົບ",
    docNo: "RC<ປປດດວວ>-#####",
    source: { label: "ຮັບສິນຄ້າ › ລາຍການຮັບ", href: "/movements/receive?tab=history" },
    owner: "keeper",
    when: "ເມື່ອ post ໃບກວດນັບ — stock ເພີ່ມທັນທີ",
    fields: ["ສາງ/location", "ລາຍການ + ຈຳນວນ", "ISN", "ຜູ້ຮັບ", "ວັນທີ່"],
    retention: "5 ປີ",
    sops: ["SOP-WH-01"],
  },
  {
    code: "F-05",
    name: "ໃບຊື້ຕິດໜີ້ (ຕັ້ງໜີ້ຜູ້ສະໜອງ)",
    kind: "ERP",
    source: { label: "ເກີດອັດຕະໂນມັດຈາກການຮັບ", href: "/movements/receive" },
    owner: "accounting",
    when: "ພ້ອມກັບການຮັບເຂົ້າ (ຕາມການຕັ້ງຄ່າ)",
    fields: ["ຜູ້ສະໜອງ", "ລາຍການ + ລາຄາ + ພາສີ", "PO ອ້າງອີງ", "ໃບ WMS ອ້າງອີງ"],
    retention: "ຕາມລະບຽບບັນຊີ",
    sops: ["SOP-WH-01"],
  },
  {
    code: "F-06",
    name: "ໃບຂໍເບີກສິນຄ້າ",
    kind: "ERP",
    source: { label: "ຈ່າຍສິນຄ້າ (ເລືອກປະເພດ ໃບຂໍເບີກ)", href: "/movements/issue" },
    owner: "sales",
    when: "ເມື່ອໜ່ວຍງານພາຍໃນຂໍເບີກສິນຄ້າ",
    fields: ["ຜູ້ຂໍ", "ສາງ", "ລາຍການ + ຈຳນວນ", "ວັນທີ່ຕ້ອງການ"],
    retention: "ຕາມລະບຽບ ERP",
    sops: ["SOP-WH-03"],
  },
  {
    code: "F-07",
    name: "ບິນຂາຍ",
    kind: "ERP",
    source: { label: "ຈ່າຍສິນຄ້າ (ເລືອກປະເພດ ບິນຂາຍ)", href: "/movements/issue" },
    owner: "sales",
    when: "ເມື່ອຂາຍໃຫ້ລູກຄ້າ",
    fields: ["ລູກຄ້າ", "ສາງ", "ລາຍການ + ຈຳນວນ", "ເລກບິນ"],
    retention: "ຕາມລະບຽບບັນຊີ",
    sops: ["SOP-WH-03", "SOP-WH-04", "SOP-WH-06"],
  },
  {
    code: "F-08",
    name: "ໃບຂໍໂອນສິນຄ້າ",
    kind: "ERP",
    source: { label: "ອອກໃບຂໍໂອນ", href: "/movements/transfer-request" },
    owner: "keeper",
    when: "ເມື່ອສາງປາຍທາງຕ້ອງການສິນຄ້າຈາກສາງອື່ນ",
    fields: ["ສາງຕົ້ນທາງ/ປາຍທາງ", "ລາຍການ + ຈຳນວນ", "ສະພາບສິນຄ້າ", "ສະຖານະອະນຸມັດ"],
    retention: "3 ປີ",
    sops: ["SOP-WH-05"],
  },
  {
    code: "F-09",
    name: "ໃບສັ່ງຈ່າຍ (ໃບ pick)",
    kind: "ລະບົບ",
    docNo: "OUT<ປປດດວວ>-#####",
    source: { label: "ຈ່າຍສິນຄ້າ › ສ້າງໃບ pick", href: "/movements/issue" },
    owner: "keeper",
    when: "ຫຼັງຈັດສັນ location/ISN ແຕ່ຍັງບໍ່ຕັດ stock",
    fields: ["ເອກະສານຕົ້ນທາງ", "ລາຍການ + location + ຈຳນວນ", "ISN ທີ່ຈອງ"],
    retention: "1 ປີ",
    sops: ["SOP-WH-03", "SOP-WH-04"],
  },
  {
    code: "F-10",
    name: "ໃບເຄື່ອນໄຫວ WMS (ຈ່າຍ / ໂອນ / ຮັບຄືນ)",
    kind: "ລະບົບ",
    docNo: "DP<ປປດດວວ>-#####",
    source: { label: "ປະຫວັດການຈ່າຍ", href: "/movements/issue?tab=history" },
    owner: "keeper",
    when: "ເມື່ອຢືນຢັນຈ່າຍ — ຕັດ stock ທັນທີ",
    fields: ["ສາງ + location", "ລາຍການ + ຈຳນວນ", "ISN", "ຜູ້ຈ່າຍ", "ເອກະສານຕົ້ນທາງ"],
    retention: "5 ປີ",
    sops: ["SOP-WH-03", "SOP-WH-05"],
  },
  {
    code: "F-11",
    name: "ໃບຈ່າຍສິນຄ້າ (ພິມໃຫ້ເຊັນຮັບ)",
    kind: "ພິມ",
    source: { label: "ປະຫວັດການຈ່າຍ", href: "/movements/issue?tab=history" },
    owner: "keeper",
    when: "ຕອນສົ່ງມອບໃຫ້ຜູ້ຮັບ",
    fields: ["ເລກໃບ", "ລາຍການ + ຈຳນວນ", "ຜູ້ຈ່າຍ / ຜູ້ຮັບ", "ລາຍເຊັນ"],
    retention: "3 ປີ (ເອກະສານເຈ້ຍ)",
    sops: ["SOP-WH-03"],
  },
  {
    code: "F-12",
    name: "ໃບຈັດຖ້ຽວ",
    kind: "ພິມ",
    source: { label: "ຈ່າຍສິນຄ້າ › ໃບຈັດຖ້ຽວ", href: "/movements/issue" },
    owner: "keeper",
    when: "ກ່ອນຈັດເຄື່ອງຂຶ້ນລົດແຕ່ລະຖ້ຽວ",
    fields: [
      "ເລກຖ້ຽວ · ລົດ · ຄົນຂັບ · ເສັ້ນທາງ",
      "ລາຍການ (ລວມແຖວ) + ບ່ອນເກັບ + ບິນຂາຍ",
      "ລາຍເຊັນ: ຜູ້ເກັບ · ຜູ້ຈ່າຍເຄື່ອງອອກສາງ · ຜູ້ກວດສອບ · ຄົນຂັບ",
    ],
    retention: "3 ປີ",
    sops: ["SOP-WH-04"],
  },
  {
    code: "F-13",
    name: "ໃບເກັບສິນຄ້າ (Pick List)",
    kind: "ພິມ",
    source: { label: "ໃບເກັບສິນຄ້າ", href: "/movements/pick" },
    owner: "picker",
    when: "ກ່ອນຍ່າງເກັບສິນຄ້າ",
    fields: ["ລາຍການ + ຈຳນວນ", "ບ່ອນເກັບ (ຮຽງຕາມເສັ້ນທາງ)", "ຜູ້ເກັບ"],
    retention: "1 ປີ",
    sops: ["SOP-WH-03"],
  },
  {
    code: "F-14",
    name: "ໃບຮັບຄືນຈາກລູກຄ້າ",
    kind: "ລະບົບ",
    docNo: "DP<ປປດດວວ>-#####",
    source: { label: "ຮັບຄືນຈາກລູກຄ້າ", href: "/movements/sale-return" },
    owner: "receiver",
    when: "ເມື່ອລູກຄ້າສົ່ງສິນຄ້າຄືນ",
    fields: ["ບິນຂາຍຕົ້ນທາງ", "ລາຍການ + ຈຳນວນ", "ISN", "ເຫດຜົນການຄືນ", "ສະພາບສິນຄ້າ"],
    retention: "5 ປີ",
    sops: ["SOP-WH-06"],
  },
  {
    code: "F-15",
    name: "ໃບຍ້າຍ Pallet",
    kind: "ລະບົບ",
    docNo: "PMV<ປປດດວວ>-#####",
    source: { label: "ຍ້າຍ Pallet", href: "/movements/pallet-move" },
    owner: "forklift",
    when: "ທຸກຄັ້ງທີ່ຍ້າຍ pallet (ລວມຂ້າມສາງ)",
    fields: ["pallet", "location ຕົ້ນທາງ/ປາຍທາງ", "ຜູ້ຍ້າຍ", "ວັນເວລາ"],
    retention: "2 ປີ",
    sops: ["SOP-WH-02"],
  },
  {
    code: "F-16",
    name: "ໃບຍ້າຍ Serial (SN vs Stock)",
    kind: "ລະບົບ",
    docNo: "SNMV<ປປດດວວ>-#####",
    source: { label: "ກວດ SN vs Stock", href: "/movements/sn-check" },
    owner: "keeper",
    when: "ເມື່ອ location ຂອງ serial ບໍ່ຕົງກັບ stock ຂອງ WMS",
    fields: ["serial", "location ເກົ່າ/ໃໝ່", "ຜູ້ດຳເນີນການ"],
    retention: "2 ປີ",
    sops: ["SOP-WH-08"],
  },
  {
    code: "F-17",
    name: "ໃບປັບປຸງ stock",
    kind: "ລະບົບ",
    docNo: "ADJ<ປປດດວວ>-#####",
    source: { label: "ປັບປຸງ stock", href: "/movements/adjust" },
    owner: "keeper",
    when: "ເມື່ອຕ້ອງແກ້ຍອດໃຫ້ຕົງກັບຂອງຈິງ (ຫຼັງໄດ້ອະນຸມັດ)",
    fields: ["ລາຍການ + ຈຳນວນກ່ອນ/ຫຼັງ", "location", "ເຫດຜົນ", "ຜູ້ປັບ + ຜູ້ອະນຸມັດ"],
    retention: "5 ປີ",
    sops: ["SOP-WH-07", "SOP-WH-08"],
  },
  {
    code: "F-18",
    name: "ຮອບກວດນັບ",
    kind: "ລະບົບ",
    docNo: "ST-<ປປດດ>-###",
    source: { label: "ຮອບກວດນັບ", href: "/stocktake" },
    owner: "supervisor",
    when: "ທຸກຮອບການນັບ (ປະຈຳເດືອນ / cycle count)",
    fields: ["ສາງ + ຂອບເຂດ", "ວັນນັບ", "ຮູບແບບ (blind ຫຼື ບໍ່)", "ຜົນນັບ + ຄວາມຕ່າງ", "ຜູ້ນັບ/ຜູ້ອະນຸມັດ"],
    retention: "5 ປີ",
    sops: ["SOP-WH-07"],
  },
  {
    code: "F-19",
    name: "ໃບຮັບຝາກເຄື່ອງ",
    kind: "ລະບົບ",
    docNo: "DP-<ປປດດ>-###",
    source: { label: "ລາຍການຝາກ", href: "/deposits" },
    owner: "keeper",
    when: "ຕອນຮັບຝາກ ແລະ ຕອນຄືນເຄື່ອງ",
    fields: ["ຜູ້ຝາກ", "ລາຍການ + ຈຳນວນ", "ວັນຝາກ/ວັນຄືນ", "ຄ່າຝາກ (THB)", "ລາຍເຊັນ"],
    retention: "3 ປີ",
    sops: ["SOP-WH-09"],
  },
  {
    code: "F-20",
    name: "ປ້າຍ pallet / location (Barcode)",
    kind: "ພິມ",
    source: { label: "ພິມ Label/Barcode", href: "/movements/labels" },
    owner: "keeper",
    when: "ເມື່ອສ້າງ pallet/location ໃໝ່ ຫຼື ປ້າຍເກົ່າເສຍຫາຍ",
    fields: ["ລະຫັດ pallet/location", "barcode Code 128", "ຊື່ສາງ"],
    retention: "ໃຊ້ຈົນກວ່າຈະປ່ຽນ",
    sops: ["SOP-WH-02"],
  },
  {
    code: "F-21",
    name: "Template Excel ຄ່າ stock ຂັ້ນຕ່ຳ/ຂັ້ນສູງ",
    kind: "Excel",
    source: { label: "ຕັ້ງຄ່າ stock ຂັ້ນຕ່ຳ/ຂັ້ນສູງ", href: "/settings/min-stock" },
    owner: "manager",
    when: "ເມື່ອຕັ້ງ ຫຼື ທົບທວນຄ່າ min/max ເປັນຊຸດ",
    fields: ["ສາງ", "ລະຫັດສິນຄ້າ", "ຂັ້ນຕ່ຳ", "ຂັ້ນສູງ", "ໝາຍເຫດ"],
    retention: "ເກັບສະບັບລ່າສຸດ",
    sops: ["SOP-WH-10"],
  },
  {
    code: "F-22",
    name: "ລາຍງານການເຄື່ອນໄຫວປະຈຳວັນ",
    kind: "ພິມ",
    source: { label: "ເຄື່ອນໄຫວປະຈຳວັນ", href: "/movements/daily" },
    owner: "supervisor",
    when: "ທຸກເຊົ້າ (ແລະ ສົ່ງທາງເມວອັດຕະໂນມັດ)",
    fields: ["ຍອດຍົກມາ", "ເປີດບິນ", "ຮັບເຂົ້າ", "ຈ່າຍອອກ", "ຍົກໄປ"],
    retention: "1 ປີ",
    sops: ["SOP-WH-10"],
  },
  {
    code: "F-23",
    name: "ລາຍງານຄ້າງຈ່າຍອອກສາງ",
    kind: "ພິມ",
    source: { label: "ຄ້າງຈ່າຍອອກສາງ", href: "/movements/pending-out" },
    owner: "supervisor",
    when: "ປະຈຳວັນ / ກ່ອນປະຊຸມ",
    fields: ["ໃບຕົ້ນທາງ", "ລູກຄ້າ/ຜູ້ຂໍ", "ລາຍການຄ້າງ", "ຈຳນວນວັນທີ່ຄ້າງ"],
    retention: "1 ປີ",
    sops: ["SOP-WH-10"],
  },
  {
    code: "F-24",
    name: "ໃບຂໍໂອນ (ພິມ)",
    kind: "ພິມ",
    source: { label: "ອອກໃບຂໍໂອນ", href: "/movements/transfer-request" },
    owner: "keeper",
    when: "ສົ່ງພ້ອມສິນຄ້າ ຫຼື ໃຫ້ສາງຕົ້ນທາງກວດ",
    fields: ["ສາງຕົ້ນທາງ/ປາຍທາງ", "ລາຍການ + ຈຳນວນ", "ຜູ້ຂໍ / ຜູ້ອະນຸມັດ"],
    retention: "3 ປີ",
    sops: ["SOP-WH-05"],
  },
  {
    code: "F-25",
    name: "ລາຍງານປະຫວັດການເຄື່ອນໄຫວ (Audit / CSV)",
    kind: "ພິມ",
    source: { label: "ປະຫວັດ (Audit)", href: "/movements/ledger" },
    owner: "manager",
    when: "ເມື່ອຕ້ອງກວດສອບ ຫຼື ສົ່ງໃຫ້ບັນຊີ/ຜູ້ກວດ",
    fields: ["ເອກະສານທັງໝົດ", "ລາຍການໃນເອກະສານ", "ຜູ້ດຳເນີນການ + ວັນເວລາ"],
    retention: "5 ປີ",
    sops: ["SOP-WH-08", "SOP-WH-11", "SOP-WH-12"],
  },
];

export const FORM_BY_CODE = new Map(FORMS.map((f) => [f.code, f]));
