import type { WorkInstruction } from "./types";

/**
 * WI (Work Instruction) — "ກົດຢູ່ໃສ ເຮັດແນວໃດ" ຕໍ່ 1 ໜ້າຈໍ / 1 ໜ້າວຽກ.
 * ສັ້ນ, ເປັນຂັ້ນຕອນ, ໃຊ້ໜ້າງານໄດ້ທັນທີ. ເຫດຜົນ ແລະ ກົດການຢູ່ SOP.
 */
export const WORK_INSTRUCTIONS: WorkInstruction[] = [
  /* ── ຮັບສິນຄ້າ ─────────────────────────────────────────────────── */
  {
    code: "WI-RCV-01",
    title: "ນຳເຂົ້າໃບ packing",
    group: "ຮັບສິນຄ້າ",
    sop: "SOP-WH-01",
    actors: ["receiver", "keeper"],
    screen: { label: "ຮັບສິນຄ້າ › ໃບ packing", href: "/movements/receive" },
    prerequisites: ["ມີ PO ທີ່ອະນຸມັດແລ້ວ", "ມີໄຟລ໌ Excel ຫຼື PDF ຈາກຜູ້ສະໜອງ"],
    steps: [
      { no: 1, action: "ເປີດ ຮັບສິນຄ້າ → ຂັ້ນ ① ໃບ packing" },
      { no: 2, action: "ເລືອກສາງ ແລະ PO ທີ່ກ່ຽວຂ້ອງ" },
      {
        no: 3,
        action: "ດາວໂຫຼດ template Excel ຕາມ PO ແລ້ວຕື່ມຈຳນວນທີ່ຜູ້ສະໜອງສົ່ງ",
        expect: "ລະຫັດ ແລະ ຊື່ສິນຄ້າມາຈາກ SML ໃຫ້ແລ້ວ",
      },
      {
        no: 4,
        action: "ອັບໄຟລ໌ຂຶ້ນລະບົບ ແລະ ແນບ PDF ຂອງຜູ້ສະໜອງ",
        warn: "ຖ້າອັບໄຟລ໌ຜູ້ສະໜອງກົງໆ ຕ້ອງຈັບຄູ່ແຕ່ລະແຖວກັບລະຫັດ SML ກ່ອນ",
      },
      { no: 5, action: "ກວດຜົນການກວດສອບ: PO ອະນຸມັດ · ລາຍການເກີນ · ຄົນລະສາງ" },
      { no: 6, action: "ບັນທຶກໃບ packing", expect: "ໄດ້ເລກໃບ PK…" },
    ],
    issues: [
      { problem: "ຂຶ້ນວ່າ PO ຍັງບໍ່ອະນຸມັດ", fix: "ຕິດຕໍ່ຈັດຊື້ໃຫ້ອະນຸມັດ — ຮັບບໍ່ໄດ້ຈົນກວ່າຈະອະນຸມັດ" },
      { problem: "ແຖວໃນ Excel ບໍ່ຈັບຄູ່ກັບສິນຄ້າ", fix: "ຈັບຄູ່ດ້ວຍມືໃນໜ້າໃບ packing — ລະບົບຈະຈື່ໄວ້ໃຫ້ຄັ້ງຕໍ່ໄປ" },
      { problem: "ຫົວຕາຕະລາງເປັນພາສາໄທ 2 ຊັ້ນ", fix: "ໃຊ້ template ຂອງລະບົບແທນ ຈະໄວກວ່າ" },
    ],
    forms: ["F-01", "F-02"],
  },
  {
    code: "WI-RCV-02",
    title: "ສ້າງ ແລະ ນັບ ໃບກວດນັບ",
    group: "ຮັບສິນຄ້າ",
    sop: "SOP-WH-01",
    actors: ["receiver"],
    screen: { label: "ຮັບສິນຄ້າ › ໃບກວດນັບ", href: "/movements/receive?tab=count" },
    prerequisites: ["ມີໃບ packing ຫຼື PO ຄ້າງຮັບ", "ສິນຄ້າມາຮອດສາງແລ້ວ"],
    steps: [
      { no: 1, action: "ກົດ ສ້າງໃບກວດນັບ ແລ້ວເລືອກສາງ" },
      {
        no: 2,
        action: "ເລືອກ PO ຈາກລາຍການຄ້າງຮັບ ຫຼື ພິມ/ຍິງເລກ PO (ໃສ່ໄດ້ຫຼາຍ PO)",
        warn: "ທຸກ PO ໃນໃບດຽວ ຕ້ອງເປັນສາງດຽວກັນ",
      },
      { no: 3, action: "ກວດລາຍການທີ່ດຶງມາ ແລະ ລຶບແຖວທີ່ບໍ່ໄດ້ຮັບອອກ" },
      { no: 4, action: "ບັນທຶກ", expect: "ໄດ້ເລກໃບ CK…" },
      { no: 5, action: "ນັບຂອງຈິງ ແລ້ວໃສ່ຈຳນວນຮັບຕໍ່ແຖວ", warn: "ຢ່າຄັດລອກຈຳນວນຈາກໃບ packing" },
      { no: 6, action: "ລາຍການ serial → ກົດຈັດການ SN ແລ້ວຍິງ/ສ້າງ ISN ໃຫ້ຄົບ" },
      { no: 7, action: "ບັນທຶກໃບກວດນັບ (ຍັງບໍ່ເຂົ້າ stock)" },
    ],
    issues: [
      { problem: "ຮັບຫຼາຍກວ່າຍອດຄ້າງຮັບ", fix: "ລະບົບເຕືອນ — ຢືນຢັນກັບຈັດຊື້ກ່ອນ ຈຶ່ງບັນທຶກ" },
      { problem: "ສິນຄ້າບໍ່ຢູ່ໃນ PO ໃດ", fix: "ຢ່າເພີ່ມເຂົ້າໃບ — ແຍກໄວ້ ແລະ ແຈ້ງຈັດຊື້" },
      { problem: "ISN ຊໍ້າ", fix: "ກວດວ່າໜ່ວຍນັ້ນຖືກຈ່າຍອອກແທ້ບໍ ກ່ອນສ້າງໃໝ່" },
    ],
    forms: ["F-03"],
  },
  {
    code: "WI-RCV-03",
    title: "Post ໃບກວດນັບ ເຂົ້າ WMS",
    group: "ຮັບສິນຄ້າ",
    sop: "SOP-WH-01",
    actors: ["keeper", "receiver"],
    screen: { label: "ຮັບສິນຄ້າ › ໃບກວດນັບ", href: "/movements/receive?tab=count" },
    prerequisites: ["ນັບຄົບທຸກແຖວ", "ISN ຄົບຕາມຈຳນວນ"],
    steps: [
      { no: 1, action: "ເປີດໃບກວດນັບທີ່ນັບແລ້ວ" },
      { no: 2, action: "ເລືອກ location / pallet ປາຍທາງ" },
      { no: 3, action: "ກົດ ຮັບເຂົ້າ WMS", expect: "ໄດ້ເລກໃບຮັບ RC… ແລະ stock ເພີ່ມທັນທີ" },
      { no: 4, action: "ກວດຢູ່ໜ້າ ຄົງເຫຼືອ ວ່າຍອດ ແລະ location ຖືກຕ້ອງ" },
      { no: 5, action: "ພິມໃບຮັບ ຖ້າຕ້ອງໃຫ້ຜູ້ສົ່ງເຊັນ" },
    ],
    issues: [
      { problem: "Post ແລ້ວພົບວ່າຈຳນວນຜິດ", fix: "ແກ້ດ້ວຍໃບປັບປຸງ (WI-ADJ-01) — ໃບທີ່ post ແລ້ວແກ້ບໍ່ໄດ້" },
      { problem: "ຂຶ້ນ error ກ່ຽວກັບ column", fix: "ແຈ້ງໄອທີ — ອາດເປັນ migration ຄ້າງ" },
    ],
    forms: ["F-03", "F-04", "F-05"],
  },
  {
    code: "WI-RCV-04",
    title: "ກວດປະຫວັດການຮັບ ແລະ ຍອດຄ້າງຮັບ",
    group: "ຮັບສິນຄ້າ",
    sop: "SOP-WH-01",
    actors: ["receiver", "supervisor"],
    screen: { label: "ຮັບສິນຄ້າ › ລາຍການຮັບສິນຄ້າ", href: "/movements/receive?tab=history" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເປີດແທັບ ລາຍການຮັບສິນຄ້າ ເພື່ອເບິ່ງໃບຮັບທີ່ຜ່ານມາ" },
      { no: 2, action: "ກົດແຖວ → ເບິ່ງລາຍການ, ຈຳນວນ, ISN ແລະ PO ທີ່ຜູກ" },
      { no: 3, action: "ໄປແທັບ ② ລາຍການຄ້າງຮັບ ເພື່ອເບິ່ງ PO ທີ່ຍັງມາບໍ່ຄົບ" },
      { no: 4, action: "ແຈ້ງຈັດຊື້ ສຳລັບ PO ທີ່ຄ້າງດົນ" },
    ],
    issues: [
      { problem: "ຮັບແລ້ວແຕ່ຍັງຂຶ້ນຄ້າງຮັບ", fix: "ກວດວ່າໃບກວດນັບຜູກກັບ PO ຖືກໃບບໍ" },
    ],
    forms: ["F-02", "F-04"],
  },

  /* ── ຈັດເກັບ ──────────────────────────────────────────────────── */
  {
    code: "WI-PUT-01",
    title: "ພິມປ້າຍ pallet / location",
    group: "ຈັດເກັບ",
    sop: "SOP-WH-02",
    actors: ["keeper", "forklift"],
    screen: { label: "ພິມ Label/Barcode", href: "/movements/labels" },
    prerequisites: ["ມີເຄື່ອງພິມ ແລະ ສະຕິກເກີ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລ້ວເລືອກປະເພດປ້າຍ (pallet ຫຼື location)" },
      { no: 2, action: "ຕິກລາຍການທີ່ຕ້ອງການ", expect: "barcode ຂຶ້ນສະແດງໃນໜ້າຈໍ" },
      { no: 3, action: "ກົດ ພິມ", expect: "ໜ້າພິມມີແຕ່ປ້າຍ ບໍ່ມີເມນູ" },
      { no: 4, action: "ຕິດປ້າຍໃສ່ pallet/ໜ້າ rack ແລ້ວທົດລອງຍິງດ້ວຍ scanner" },
    ],
    issues: [
      { problem: "scanner ອ່ານປ້າຍບໍ່ໄດ້", fix: "ພິມໃໝ່ໃຫ້ຄົມຂຶ້ນ ຫຼື ຂະຫຍາຍຂະໜາດ ຫ້າມຂຽນມືທົດແທນ" },
    ],
    forms: ["F-20"],
  },
  {
    code: "WI-PUT-02",
    title: "ປະກອບ pallet (ໂຫລດສິນຄ້າ)",
    group: "ຈັດເກັບ",
    sop: "SOP-WH-02",
    actors: ["keeper"],
    screen: { label: "ປະກອບ Pallet", href: "/movements/pallet-load" },
    prerequisites: ["pallet ມີປ້າຍແລ້ວ", "ສິນຄ້າຢູ່ພື້ນທີ່ຮັບ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລະ ຍິງ/ເລືອກ pallet", expect: "ສະແດງບ່ອນປັດຈຸບັນຂອງ pallet" },
      { no: 2, action: "ຍິງ barcode ສິນຄ້າ ຫຼື ຄົ້ນຫາລະຫັດ" },
      { no: 3, action: "ໃສ່ຈຳນວນ; ລາຍການ serial ໃຫ້ກົດ ຈັດການ SN ແລ້ວຍິງ ISN" },
      { no: 4, action: "ບັນທຶກ", expect: "stock ໄປຢູ່ບ່ອນຂອງ pallet ແລະ ມີໃບໃນປະຫວັດ" },
    ],
    issues: [
      { problem: "ຍິງ ISN ແລ້ວແຈ້ງວ່າບໍ່ຢູ່ໃນສາງ", fix: "ກວດວ່າໜ່ວຍນັ້ນຖືກຮັບເຂົ້າແລ້ວບໍ ຫຼື ຖືກຈ່າຍອອກໄປແລ້ວ" },
    ],
    forms: ["F-17"],
  },
  {
    code: "WI-PUT-03",
    title: "ຍ້າຍ pallet",
    group: "ຈັດເກັບ",
    sop: "SOP-WH-02",
    actors: ["forklift", "keeper"],
    screen: { label: "ຍ້າຍ Pallet", href: "/movements/pallet-move" },
    prerequisites: ["ຮູ້ location ປາຍທາງ"],
    steps: [
      { no: 1, action: "ຍິງ/ເລືອກ pallet ທີ່ຈະຍ້າຍ" },
      { no: 2, action: "ຍິງ/ເລືອກ location ປາຍທາງ (ຂ້າມສາງໄດ້)" },
      { no: 3, action: "ຢືນຢັນ", expect: "ໄດ້ໃບ PMV… ແລະ ສິນຄ້າ+serial ຍ້າຍຕາມ pallet" },
      { no: 4, action: "ຍ້າຍຂອງຈິງໃຫ້ຕົງກັບທີ່ບັນທຶກ" },
    ],
    issues: [
      { problem: "ຍ້າຍຂອງແລ້ວແຕ່ລືມບັນທຶກ", fix: "ບັນທຶກຍ້ອນຫຼັງທັນທີ ແລ້ວແຈ້ງ Supervisor ໃຫ້ກວດ SN ທຽບ stock" },
      { problem: "location ປາຍທາງເຕັມ", fix: "ຫາບ່ອນອື່ນຜ່ານໜ້າ Putaway" },
    ],
    forms: ["F-15"],
  },
  {
    code: "WI-PUT-04",
    title: "ຫາບ່ອນວ່າງ (Putaway)",
    group: "ຈັດເກັບ",
    sop: "SOP-WH-02",
    actors: ["forklift"],
    screen: { label: "ບ່ອນວ່າງ (Putaway)", href: "/movements/putaway" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເລືອກສາງ", expect: "ເຫັນ KPI ວ່າງ / ມີສິນຄ້າ / % ການໃຊ້" },
      { no: 2, action: "ຕິກ ສະແດງແຕ່ບ່ອນວ່າງ ຫຼື ຄົ້ນຫາ rack ທີ່ຕ້ອງການ" },
      { no: 3, action: "ເລືອກ location ທີ່ເໝາະກັບນ້ຳໜັກ-ຂະໜາດ ແລ້ວນຳໄປໃຊ້ໃນການຍ້າຍ pallet" },
    ],
    issues: [{ problem: "ບໍ່ມີບ່ອນວ່າງເລີຍ", fix: "ແຈ້ງ Supervisor ຈັດພື້ນທີ່ ຫຼື ລະບາຍສິນຄ້າຄ້າງ" }],
    forms: [],
  },

  /* ── ຈ່າຍສິນຄ້າ ───────────────────────────────────────────────── */
  {
    code: "WI-ISS-01",
    title: "ສ້າງໃບສັ່ງຈ່າຍຈາກເອກະສານອ້າງອີງ",
    group: "ຈ່າຍສິນຄ້າ",
    sop: "SOP-WH-03",
    actors: ["keeper"],
    screen: { label: "ຈ່າຍສິນຄ້າ › ສ້າງໃບ pick", href: "/movements/issue" },
    prerequisites: ["ມີ ໃບຂໍເບີກ / ບິນຂາຍ / ໃບຂໍໂອນທີ່ອະນຸມັດແລ້ວ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລະ ປະເພດເອກະສານ: ບິນຂາຍ · ໃບຂໍເບີກ · ໃບຂໍໂອນ" },
      { no: 2, action: "ເລືອກໃບຕົ້ນທາງ", expect: "ສະແດງລາຍການພ້ອມຍອດຄ້າງຈ່າຍ" },
      {
        no: 3,
        action: "ຕໍ່ແຖວ: ເລືອກ location ຕົ້ນທາງ ແລະ ໃສ່ຈຳນວນ",
        expect: "⭐ ໝາຍ location ທີ່ຄວນເກັບກ່ອນ (FEFO)",
        warn: "ຈຳນວນຫ້າມເກີນຍອດຄ້າງຈ່າຍ ຫຼື ຍອດຂອງ location",
      },
      { no: 4, action: "ລາຍການ serial → ເລືອກ ISN ເອງ ຫຼື ປະໄວ້ໃຫ້ລະບົບຈອງແບບ FIFO" },
      { no: 5, action: "ບັນທຶກ", expect: "ໄດ້ໃບສັ່ງຈ່າຍ OUT… (ຍັງບໍ່ຕັດ stock)" },
    ],
    issues: [
      { problem: "ບໍ່ເຫັນໃບຂໍໂອນ", fix: "ກວດວ່າໃບບໍ່ຖືກປະຕິເສດ ແລະ ວັນທີໃບຢູ່ໃນຊ່ວງທີ່ລະບົບເບິ່ງຄືນຫຼັງ" },
      { problem: "ຍອດຄ້າງຈ່າຍບໍ່ຕົງກັບຄວາມຈິງ", fix: "ກວດວ່າມີໃບຈ່າຍເກົ່າອ້າງໃບດຽວກັນບໍ ໃນປະຫວັດການຈ່າຍ" },
    ],
    forms: ["F-06", "F-07", "F-08", "F-09"],
  },
  {
    code: "WI-ISS-02",
    title: "ຢືນຢັນຈ່າຍ ໂດຍຍິງ ISN",
    group: "ຈ່າຍສິນຄ້າ",
    sop: "SOP-WH-03",
    actors: ["picker", "keeper"],
    screen: { label: "ຈ່າຍສິນຄ້າ › ຢືນຢັນຈ່າຍ", href: "/movements/issue?tab=pending" },
    prerequisites: ["ມີໃບສັ່ງຈ່າຍ OUT ທີ່ຍັງບໍ່ຢືນຢັນ", "ເກັບສິນຄ້າມາຮອດຈຸດຈ່າຍແລ້ວ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລ້ວເປີດໃບສັ່ງຈ່າຍທີ່ຈະຢືນຢັນ" },
      { no: 2, action: "ຍິງ ISN ທຸກໜ່ວຍທີ່ຈັດສັນໄວ້", expect: "ລາຍການທີ່ຍິງແລ້ວຈະຖືກໝາຍ" },
      { no: 3, action: "ກົດ ຢືນຢັນຈ່າຍ", expect: "ໄດ້ໃບຈ່າຍ DP… · stock ຫຼຸດ · ISN ປ່ຽນເປັນຈ່າຍອອກ" },
      { no: 4, action: "ພິມໃບຈ່າຍ ໃຫ້ຜູ້ຮັບເຊັນ" },
    ],
    issues: [
      { problem: "ຢືນຢັນບໍ່ໄດ້ ບອກວ່າ ISN ບໍ່ຄົບ", fix: "ຍິງໃຫ້ຄົບທຸກໜ່ວຍ — ຫຼື ແກ້ການຈັດສັນຖ້າຂອງມາຈາກ location ອື່ນ" },
      { problem: "ຂອງບໍ່ພໍ", fix: "ຫຼຸດຈຳນວນໃນໃບ ແລ້ວລະບຸເຫດຜົນ; ສ່ວນທີ່ເຫຼືອຄ້າງໄວ້ຈ່າຍພາຍຫຼັງ" },
      { problem: "ຢືນຢັນຜິດໃບ", fix: "ຂໍຜູ້ມີສິດລົບໃບຈ່າຍ (WI-ISS-06) ແລ້ວເຮັດໃໝ່" },
    ],
    forms: ["F-09", "F-10", "F-11"],
  },
  {
    code: "WI-ISS-03",
    title: "ຈ່າຍແບບເລືອກເອງຈາກ stock",
    group: "ຈ່າຍສິນຄ້າ",
    sop: "SOP-WH-03",
    actors: ["keeper"],
    screen: { label: "ຈ່າຍສິນຄ້າ", href: "/movements/issue" },
    prerequisites: ["ໄດ້ຮັບອະນຸຍາດຈາກ Supervisor", "ມີເອກະສານພາຍໃນອ້າງອີງ"],
    steps: [
      { no: 1, action: "ເລືອກໂໝດ ເລືອກເອງຈາກ stock" },
      { no: 2, action: "ເລືອກສາງ → rack → location ແລ້ວເລືອກລາຍການ" },
      { no: 3, action: "ໃສ່ຈຳນວນ ແລະ ເລືອກ ISN (ຖ້າມີ)" },
      { no: 4, action: "ໃສ່ເຫດຜົນ/ຜູ້ຮັບ ແລ້ວບັນທຶກ" },
    ],
    issues: [
      { problem: "ໃຊ້ໂໝດນີ້ແທນເອກະສານຈິງ", fix: "ຫ້າມ — ໃຊ້ສະເພາະກໍລະນີພິເສດທີ່ Supervisor ອະນຸຍາດ" },
    ],
    forms: ["F-10"],
  },
  {
    code: "WI-ISS-04",
    title: "ພິມ ແລະ ໃຊ້ ໃບເກັບສິນຄ້າ (Pick List)",
    group: "ຈ່າຍສິນຄ້າ",
    sop: "SOP-WH-03",
    actors: ["picker"],
    screen: { label: "ໃບເກັບສິນຄ້າ", href: "/movements/pick" },
    prerequisites: ["ມີໃບສັ່ງຈ່າຍ ຫຼື ເອກະສານຕົ້ນທາງ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລະ ໃບທີ່ຈະເກັບ" },
      { no: 2, action: "ພິມໃບເກັບ", expect: "ລາຍການຮຽງຕາມ location ໃຫ້ຍ່າງຮອບດຽວ" },
      { no: 3, action: "ເກັບຕາມລຳດັບ ແລະ ໝາຍທຸກແຖວທີ່ເກັບແລ້ວ" },
      { no: 4, action: "ນຳໄປຈຸດຈ່າຍ ແລ້ວດຳເນີນຕໍ່ຕາມ WI-ISS-02" },
    ],
    issues: [
      { problem: "ບໍ່ພົບຂອງທີ່ location", fix: "ຢ່າໄປເອົາ location ອື່ນເອງ — ແຈ້ງ Supervisor ກ່ອນ" },
    ],
    forms: ["F-13"],
  },
  {
    code: "WI-ISS-05",
    title: "ໃບຈັດຖ້ຽວ (Trip Pick)",
    group: "ຈ່າຍສິນຄ້າ",
    sop: "SOP-WH-04",
    actors: ["keeper", "picker"],
    screen: { label: "ຈ່າຍສິນຄ້າ › ໃບຈັດຖ້ຽວ", href: "/movements/issue" },
    prerequisites: ["ຂົນສົ່ງສ້າງຖ້ຽວແລ້ວ ແລະ ຍັງບໍ່ເລີ່ມຈັດສົ່ງ"],
    steps: [
      { no: 1, action: "ເລືອກປະເພດ ໃບຈັດຖ້ຽວ ແລ້ວເລືອກຖ້ຽວ", expect: "ເຫັນລົດ · ຄົນຂັບ · ເສັ້ນທາງ · ບິນໃນຖ້ຽວ" },
      { no: 2, action: "ກວດຈຳນວນຕໍ່ບິນ ແລະ ປັບຖ້າຈຳເປັນ" },
      { no: 3, action: "ບັນທຶກເປັນໃບສັ່ງຈ່າຍໃບດຽວຂອງຖ້ຽວ" },
      { no: 4, action: "ພິມໃບຈັດຖ້ຽວ", expect: "ລວມແຖວທີ່ສິນຄ້າ+ບ່ອນເກັບດຽວກັນ ແລະ ຮຽງຕາມບ່ອນເກັບ" },
      { no: 5, action: "ເກັບ → ຢືນຢັນຈ່າຍ (ຍິງ ISN)", expect: "ລະບົບແຍກໃບຈ່າຍຕໍ່ບິນໃຫ້ອັດຕະໂນມັດ" },
      { no: 6, action: "ໃຫ້ຄົນຂັບກວດຮັບ ແລະ ເຊັນຮັບໃນໃບ" },
    ],
    issues: [
      { problem: "ບໍ່ເຫັນຖ້ຽວທີ່ຕ້ອງການ", fix: "ຖ້ຽວທີ່ເລີ່ມຈັດສົ່ງແລ້ວຈະບໍ່ຂຶ້ນ — ປັບຕົວກັ່ນຕອງ ຫຼື ຕິດຕໍ່ຂົນສົ່ງ" },
      { problem: "1 ບິນ ຢູ່ຫຼາຍຖ້ຽວ", fix: "ເປັນເລື່ອງປົກກະຕິ — ຈ່າຍຕາມຈຳນວນຂອງແຕ່ລະຖ້ຽວ" },
    ],
    forms: ["F-12"],
  },
  {
    code: "WI-ISS-06",
    title: "ລົບ / ຍົກເລີກ ໃບຈ່າຍ",
    group: "ຈ່າຍສິນຄ້າ",
    sop: "SOP-WH-03",
    actors: ["manager", "supervisor"],
    screen: { label: "ຈ່າຍສິນຄ້າ › ປະຫວັດການຈ່າຍ", href: "/movements/issue?tab=history" },
    prerequisites: ["ໄດ້ຮັບສິດລົບ", "ມີການອະນຸມັດ ແລະ ເຫດຜົນ"],
    steps: [
      { no: 1, action: "ຫາໃບຈ່າຍໃນປະຫວັດ (ຄົ້ນຫາດ້ວຍເລກໃບ/ບິນ/ຖ້ຽວ)" },
      { no: 2, action: "ກວດວ່າສິນຄ້າກັບຄືນສາງແທ້ ກ່ອນລົບ" },
      { no: 3, action: "ກົດ ລົບ ພ້ອມລະບຸເຫດຜົນ", expect: "stock ຄືນ · ISN ກັບເປັນຄົງເຫຼືອ · ເອກະສານ ERP ຖືກຍົກເລີກ" },
      { no: 4, action: "ບັນທຶກໃໝ່ໃຫ້ຖືກຕ້ອງ" },
    ],
    issues: [
      { problem: "ບໍ່ມີປຸ່ມລົບ", fix: "ຕ້ອງໃຫ້ຜູ້ຈັດການມອບສິດໃນໜ້າ ຈັດການສິດເຂົ້າເຖິງ" },
      { problem: "ຂອງອອກຈາກສາງໄປແລ້ວ", fix: "ຢ່າລົບ — ໃຫ້ໃຊ້ຂະບວນການຮັບຄືນແທນ" },
    ],
    forms: ["F-10"],
  },

  /* ── ໂອນສາງ ───────────────────────────────────────────────────── */
  {
    code: "WI-TRF-01",
    title: "ອອກໃບຂໍໂອນ",
    group: "ໂອນສາງ",
    sop: "SOP-WH-05",
    actors: ["keeper"],
    screen: { label: "ອອກໃບຂໍໂອນ", href: "/movements/transfer-request" },
    prerequisites: ["ຮູ້ສາງຕົ້ນທາງ ແລະ ລາຍການທີ່ຕ້ອງການ"],
    steps: [
      { no: 1, action: "ເລືອກສາງປາຍທາງ (ສາງຕົນ) ແລະ ສາງຕົ້ນທາງ" },
      { no: 2, action: "ເພີ່ມລາຍການ ພ້ອມຈຳນວນ ແລະ ສະພາບສິນຄ້າຕໍ່ແຖວ" },
      { no: 3, action: "ບັນທຶກ", expect: "ໃບຢູ່ສະຖານະ ລໍຖ້າອະນຸມັດ" },
      { no: 4, action: "ພິມ/ສົ່ງໃຫ້ສາງຕົ້ນທາງ ຖ້າຈຳເປັນ" },
    ],
    issues: [
      { problem: "ຕ້ອງແກ້ໃບຫຼັງສົ່ງ", fix: "ແກ້ໄດ້ຖ້າຍັງບໍ່ມີການເຄື່ອນໄຫວ — ແຕ່ຈະກັບໄປລໍຖ້າອະນຸມັດໃໝ່" },
    ],
    forms: ["F-08", "F-24"],
  },
  {
    code: "WI-TRF-03",
    title: "ຈ່າຍໂອນອອກ (ໄປສາງລະຫວ່າງທາງ)",
    group: "ໂອນສາງ",
    sop: "SOP-WH-05",
    actors: ["keeper"],
    screen: { label: "ຈ່າຍສິນຄ້າ", href: "/movements/issue" },
    prerequisites: ["ໃບຂໍໂອນ ອະນຸມັດແລ້ວ"],
    steps: [
      { no: 1, action: "ເລືອກປະເພດ ໃບຂໍໂອນ ແລ້ວເລືອກໃບ" },
      { no: 2, action: "ຈັດສັນ location ແລະ ຈຳນວນ ຕາມ WI-ISS-01" },
      { no: 3, action: "ຢືນຢັນຈ່າຍ (ຍິງ ISN)", expect: "ຂອງໄປພັກຢູ່ສາງລະຫວ່າງທາງ 9903" },
      { no: 4, action: "ສົ່ງເອກະສານໄປພ້ອມກັບຂອງ" },
    ],
    issues: [
      { problem: "ຈ່າຍແລ້ວ ປາຍທາງບອກວ່າບໍ່ໄດ້ຮັບ", fix: "ກວດ dashboard — ຖ້າຍັງຄ້າງທີ່ 9903 ໃຫ້ຕິດຕາມຂົນສົ່ງ ຫຼື ດຶງກັບຄືນ (WI-TRF-05)" },
    ],
    forms: ["F-08", "F-10"],
  },
  {
    code: "WI-TRF-04",
    title: "ຮັບໂອນເຂົ້າສາງ",
    group: "ໂອນສາງ",
    sop: "SOP-WH-05",
    actors: ["keeper", "receiver"],
    screen: { label: "ຮັບໂອນເຂົ້າສາງ", href: "/movements/transfer-receive" },
    prerequisites: ["ຂອງມາຮອດສາງປາຍທາງ"],
    steps: [
      { no: 1, action: "ເລືອກສາງຕົນ ແລ້ວເປີດໃບທີ່ຄ້າງລະຫວ່າງທາງ" },
      { no: 2, action: "ນັບຂອງຈິງ ແລ້ວໃສ່ຈຳນວນທີ່ຮັບ (ຮັບບໍ່ຄົບໄດ້)" },
      { no: 3, action: "ຍິງ ISN ຂອງລາຍການ serial" },
      { no: 4, action: "ບັນທຶກ", expect: "stock ເຂົ້າສາງຕົນ · ສ່ວນທີ່ເຫຼືອຍັງຄ້າງລະຫວ່າງທາງ" },
      { no: 5, action: "ຈັດເກັບເຂົ້າ location (WI-PUT-03)" },
    ],
    issues: [
      { problem: "ຂອງມາຫຼາຍກວ່າທີ່ຈ່າຍ", fix: "ຮັບບໍ່ໄດ້ — ນັບຊ້ຳທັງສອງສາງ ແລ້ວແກ້ດ້ວຍໃບປັບປຸງ ຖ້າຢືນຢັນແລ້ວ" },
    ],
    forms: ["F-10"],
  },
  {
    code: "WI-TRF-05",
    title: "ຮັບຄືນສ່ວນຄ້າງລະຫວ່າງທາງ",
    group: "ໂອນສາງ",
    sop: "SOP-WH-05",
    actors: ["keeper"],
    screen: { label: "ຮັບຄືນຈາກການຈ່າຍ", href: "/movements/transfer-return" },
    prerequisites: ["ຂອງກັບມາຮອດສາງຕົ້ນທາງແລ້ວ"],
    steps: [
      { no: 1, action: "ເລືອກສາງຕົ້ນທາງ ແລ້ວເປີດໃບທີ່ຍັງມີຍອດຄ້າງ" },
      { no: 2, action: "ໃສ່ຈຳນວນທີ່ຮັບຄືນ ແລະ ຍິງ ISN" },
      { no: 3, action: "ບັນທຶກ", expect: "ຍອດຄ້າງລະຫວ່າງທາງຫຼຸດລົງ · stock ກັບເຂົ້າສາງຕົ້ນທາງ" },
    ],
    issues: [
      { problem: "ຍອດຄ້າງບໍ່ເປັນ 0 ຫຼັງຮັບຄືນ", fix: "ກວດວ່າປາຍທາງຮັບບາງສ່ວນໄປແລ້ວບໍ — ຍອດຕ້ອງ = ຮັບ + ຮັບຄືນ" },
    ],
    forms: ["F-10"],
  },

  /* ── ຮັບຄືນ ───────────────────────────────────────────────────── */
  {
    code: "WI-RET-01",
    title: "ຮັບຄືນຈາກລູກຄ້າ",
    group: "ຮັບຄືນ",
    sop: "SOP-WH-06",
    actors: ["receiver", "keeper"],
    screen: { label: "ຮັບຄືນຈາກລູກຄ້າ", href: "/movements/sale-return" },
    prerequisites: ["ມີບິນຂາຍຕົ້ນທາງ", "ຂາຍອະນຸມັດການຄືນແລ້ວ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລະ ຄົ້ນຫາບິນຂາຍ" },
      { no: 2, action: "ໃສ່ຈຳນວນທີ່ຮັບຄືນຕໍ່ລາຍການ ແລະ ເລືອກ location ປາຍທາງ" },
      { no: 3, action: "ຍິງ ISN ທີ່ຄືນ", warn: "ຕ້ອງເປັນ ISN ທີ່ຈ່າຍອອກໄປແທ້" },
      { no: 4, action: "ບັນທຶກ", expect: "stock ເພີ່ມ · serial ກັບເປັນ ຄົງເຫຼືອໃນສາງ" },
      { no: 5, action: "ພິມໃບ ແລະ ແຈ້ງບັນຊີໃຫ້ອອກໃບຫຼຸດໜີ້ໃນ SmartBiz" },
    ],
    issues: [
      { problem: "ຂອງເສຍຫາຍ", fix: "ຮັບເຂົ້າແຍກເປັນຂອງເສຍ ບໍ່ນຳໄປຂາຍ ແລະ ແຈ້ງ Supervisor" },
      { problem: "ບໍ່ພົບບິນຂາຍ", fix: "ໃຫ້ຂາຍຢືນຢັນເລກບິນ — ບໍ່ມີບິນ ຮັບຄືນບໍ່ໄດ້" },
    ],
    forms: ["F-14"],
  },

  /* ── ກວດນັບ ───────────────────────────────────────────────────── */
  {
    code: "WI-CNT-01",
    title: "ສ້າງຮອບກວດນັບ",
    group: "ກວດນັບ",
    sop: "SOP-WH-07",
    actors: ["supervisor", "manager"],
    screen: { label: "ສ້າງຮອບໃໝ່", href: "/stocktake/new" },
    prerequisites: ["ມີແຜນນັບ ແລະ ທີມນັບ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ, ຕັ້ງຊື່ຮອບ ແລະ ວັນນັບ" },
      { no: 2, action: "ເລືອກຮູບແບບ: ນັບປິດຕາ (blind) ຫຼື ເຫັນຍອດລະບົບ" },
      { no: 3, action: "ກຳນົດຂອບເຂດ (rack/location/ໝວດສິນຄ້າ)" },
      { no: 4, action: "ບັນທຶກ", expect: "ໄດ້ຮອບ ST-… ສະຖານະ ເປີດ" },
    ],
    issues: [
      { problem: "ບໍ່ຮູ້ຄວນເລືອກ blind ບໍ", fix: "ນັບປະຈຳເດືອນ/ຕ້ອງການຄວາມເປັນກາງ → ໃຊ້ blind" },
    ],
    forms: ["F-18"],
  },
  {
    code: "WI-CNT-02",
    title: "ນັບ ແລະ ປິດຮອບ",
    group: "ກວດນັບ",
    sop: "SOP-WH-07",
    actors: ["counter", "supervisor", "manager"],
    screen: { label: "ຮອບກວດນັບ", href: "/stocktake" },
    prerequisites: ["ຮອບຢູ່ສະຖານະ ເປີດ"],
    steps: [
      { no: 1, action: "ເປີດຮອບ ແລ້ວເລືອກ location ທີ່ຈະນັບ" },
      { no: 2, action: "ນັບຂອງຈິງ ແລ້ວໃສ່ຈຳນວນ; ລາຍການ serial ຍິງ ISN" },
      { no: 3, action: "ນັບຊ້ຳລາຍການທີ່ຕ່າງ ໂດຍຄົນທີ 2" },
      { no: 4, action: "Supervisor ກົດ ສົ່ງເພື່ອຂໍອະນຸມັດ", warn: "ຫຼັງສົ່ງແລ້ວ ແກ້ບໍ່ໄດ້" },
      { no: 5, action: "ຜູ້ຈັດການ ອະນຸມັດ → ຄວາມຕ່າງຖືກປັບເຂົ້າ stock ແລະ ຮອບຖືກປິດ" },
    ],
    issues: [
      { problem: "ນັບໄດ້ໜ້ອຍກວ່າ", fix: "ຄົ້ນ location ໃກ້ຄຽງ ແລະ ກວດເອກະສານຈ່າຍລ່າສຸດ ກ່ອນສະຫຼຸບວ່າຂາດ" },
      { problem: "ນັບໄດ້ຫຼາຍກວ່າ", fix: "ກວດວ່າມີການຮັບທີ່ຍັງບໍ່ບັນທຶກບໍ" },
    ],
    forms: ["F-18", "F-17"],
  },

  /* ── ປັບປຸງ ───────────────────────────────────────────────────── */
  {
    code: "WI-ADJ-01",
    title: "ບັນທຶກໃບປັບປຸງ stock",
    group: "ປັບປຸງ",
    sop: "SOP-WH-08",
    actors: ["keeper"],
    screen: { label: "ປັບປຸງ stock", href: "/movements/adjust" },
    prerequisites: ["ນັບຊ້ຳຢືນຢັນແລ້ວ", "ໄດ້ຮັບການອະນຸມັດ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ → rack → location ແລະ ລາຍການ" },
      { no: 2, action: "ໃສ່ຈຳນວນທີ່ຖືກຕ້ອງ (ຫຼື ຈຳນວນທີ່ປັບເພີ່ມ/ຫຼຸດ)" },
      { no: 3, action: "ລາຍການ serial → ຈັດການ ISN ໃຫ້ຕົງກັບຂອງຈິງ" },
      { no: 4, action: "ໃສ່ເຫດຜົນ ແລະ ອ້າງອີງການອະນຸມັດ ແລ້ວບັນທຶກ" },
      { no: 5, action: "ກວດຢູ່ ຄົງເຫຼືອ ແລະ ປະຫວັດ (Audit) ວ່າຖືກຕ້ອງ" },
    ],
    issues: [
      { problem: "ປັບຜິດ", fix: "ລົບ/ຍົກເລີກໃບໃນມື້ດຽວກັນ ແລ້ວບັນທຶກໃໝ່" },
      { problem: "ຕ້ອງປັບຫຼາຍລາຍການ", fix: "ໃຊ້ຮອບກວດນັບແທນ ຈະມີການອະນຸມັດ ແລະ ຫຼັກຖານດີກວ່າ" },
    ],
    forms: ["F-17"],
  },
  {
    code: "WI-ADJ-02",
    title: "ກວດ SN ທຽບ Stock ແລະ ຍ້າຍ SN ໃຫ້ຕົງ",
    group: "ປັບປຸງ",
    sop: "SOP-WH-08",
    actors: ["keeper", "supervisor"],
    screen: { label: "ກວດ SN vs Stock", href: "/movements/sn-check" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເລືອກສາງ", expect: "ສະແດງ location ທີ່ SN ≠ stock ຂອງ WMS" },
      { no: 2, action: "ກວດຂອງຈິງກ່ອນ ວ່າຢູ່ບ່ອນໃດແທ້" },
      { no: 3, action: "ປັບອັດຕະໂນມັດ (ຍ້າຍ SN ໄປຕາມ WMS) ຫຼື ປັບດ້ວຍມືໂດຍຍິງ SN ໃສ່ location" },
      { no: 4, action: "ບັນທຶກ", expect: "ໄດ້ໃບ SNMV… ໃນປະຫວັດ" },
    ],
    issues: [
      { problem: "ປັບແລ້ວຮູ້ວ່າ WMS ຕ່າງຫາກທີ່ຜິດ", fix: "ໃຊ້ຟັງຊັນ undo/ລົບໃບ SNMV ແລ້ວແກ້ location ຂອງ stock ແທນ" },
      { problem: "ຈຳນວນ SN ເກີນຄວາມຈຸ location", fix: "ແບ່ງໄປ location ອື່ນ ແລະ ບັນທຶກການຍ້າຍ" },
    ],
    forms: ["F-16"],
  },
  {
    code: "WI-ADJ-03",
    title: "ກວດຄວາມຖືກຕ້ອງ stock (WMS ↔ ERP ↔ SN)",
    group: "ປັບປຸງ",
    sop: "SOP-WH-08",
    actors: ["manager", "supervisor"],
    screen: { label: "ຄວາມຖືກຕ້ອງ stock", href: "/movements/accuracy" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລ້ວລໍໃຫ້ຂໍ້ມູນໂຫລດ", warn: "ຂໍ້ມູນ ERP ຊ້າ — ລະບົບ cache ໄວ້ປະມານ 10 ນາທີ" },
      { no: 2, action: "ເບິ່ງ % ຄວາມແມ່ນຍຳ ແລະ ລາຍການທີ່ບໍ່ກົງ" },
      { no: 3, action: "ແຍກສາເຫດ: SN ຜິດບ່ອນ · ເອກະສານຂາດ · ຈຳນວນຜິດຈິງ" },
      { no: 4, action: "ດຳເນີນການຕາມ WI-ADJ-02 ຫຼື WI-ADJ-01 ຕາມກໍລະນີ" },
    ],
    issues: [
      { problem: "ໜ້າໂຫລດຊ້າ", fix: "ເປັນຂໍ້ຈຳກັດຂອງ ERP — ຫຼີກລ້ຽງກົດຊ້ຳ ແລະ ໃຊ້ຜົນທີ່ cache ໄວ້" },
    ],
    forms: ["F-25"],
  },

  /* ── ຝາກເຄື່ອງ ────────────────────────────────────────────────── */
  {
    code: "WI-DEP-01",
    title: "ຮັບຝາກ ແລະ ຄືນເຄື່ອງຝາກ",
    group: "ຝາກເຄື່ອງ",
    sop: "SOP-WH-09",
    actors: ["keeper"],
    screen: { label: "ຮັບຝາກໃໝ່", href: "/deposits/new" },
    prerequisites: ["ມີຂໍ້ມູນຜູ້ຝາກ"],
    steps: [
      { no: 1, action: "ກົດ ຮັບຝາກໃໝ່ ແລ້ວປ້ອນຜູ້ຝາກ, ລາຍການ, ຈຳນວນ ແລະ ບ່ອນເກັບ" },
      { no: 2, action: "ບັນທຶກ ແລ້ວພິມໃບຮັບຝາກໃຫ້ຜູ້ຝາກເຊັນ" },
      { no: 3, action: "ຕິດຕາມໃນລາຍການຝາກ", expect: "ເກີນມື້ຟຣີຈະຂຶ້ນສີແດງ" },
      { no: 4, action: "ຕອນຄືນ: ຢືນຢັນຕົວຕົນ → ນັບເຄື່ອງ → ປິດລາຍການ", expect: "ລະບົບຄິດຄ່າຝາກເປັນ THB ຕາມຂັ້ນວັນ" },
    ],
    issues: [
      { problem: "ຜູ້ມາຮັບບໍ່ແມ່ນຜູ້ຝາກ", fix: "ຕ້ອງມີໜັງສືມອບສິດ + ບັດປະຈຳຕົວ" },
      { problem: "ຕ້ອງຍົກເວັ້ນຄ່າຝາກ", fix: "ຂໍອະນຸມັດຈາກຜູ້ຈັດການ ແລະ ບັນທຶກເຫດຜົນ" },
    ],
    forms: ["F-19"],
  },

  /* ── ລາຍງານ ───────────────────────────────────────────────────── */
  {
    code: "WI-RPT-01",
    title: "ເບິ່ງຄົງເຫຼືອ ແລະ ຄົ້ນຫາສິນຄ້າ",
    group: "ລາຍງານ",
    sop: "SOP-WH-10",
    actors: ["keeper", "supervisor", "manager"],
    screen: { label: "ຄົງເຫຼືອ", href: "/movements/balance" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເລືອກສາງ ຫຼື ເຈາະເບິ່ງເປັນ rack / location" },
      { no: 2, action: "ຄົ້ນຫາດ້ວຍ ລະຫັດ / ຊື່ສິນຄ້າ" },
      { no: 3, action: "ເບິ່ງຈຳນວນຄົງເຫຼືອ, ປ້າຍເຕືອນ stock ຂັ້ນຕ່ຳ ແລະ ISN ທີ່ຢູ່ໃນບ່ອນນັ້ນ" },
    ],
    issues: [
      { problem: "ບໍ່ເຫັນສາງທີ່ຕ້ອງການ", fix: "ຕ້ອງໃຫ້ຜູ້ຈັດການມອບໝາຍສາງໃຫ້ບັນຊີຂອງທ່ານກ່ອນ" },
    ],
    forms: [],
  },
  {
    code: "WI-RPT-02",
    title: "ອ່ານລາຍງານການເຄື່ອນໄຫວປະຈຳວັນ",
    group: "ລາຍງານ",
    sop: "SOP-WH-10",
    actors: ["supervisor", "manager"],
    screen: { label: "ເຄື່ອນໄຫວປະຈຳວັນ", href: "/movements/daily" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລະ ຊ່ວງວັນທີ່" },
      { no: 2, action: "ອ່ານຄໍລຳ: ຍອດຍົກມາ · ເປີດບິນ · ຮັບເຂົ້າ · ຈ່າຍອອກ · ຍົກໄປ" },
      { no: 3, action: "ກົດວັນທີ່ ເພື່ອເບິ່ງລາຍລະອຽດຂອງມື້ນັ້ນ" },
      { no: 4, action: "ພິມ ຫຼື ສົ່ງຕໍ່ໃຫ້ຜູ້ກ່ຽວຂ້ອງ" },
    ],
    issues: [
      { problem: "ຍອດຍົກໄປບໍ່ຕົງກັບຄົງເຫຼືອ", fix: "ກວດວ່າມີເອກະສານທີ່ບັນທຶກຍ້ອນຫຼັງບໍ ແລ້ວແຈ້ງຜູ້ຈັດການ" },
    ],
    forms: ["F-22"],
  },
  {
    code: "WI-RPT-03",
    title: "ຕິດຕາມ ໃບຄ້າງຈ່າຍອອກສາງ",
    group: "ລາຍງານ",
    sop: "SOP-WH-10",
    actors: ["supervisor", "sales"],
    screen: { label: "ຄ້າງຈ່າຍອອກສາງ", href: "/movements/pending-out" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເລືອກມຸມມອງ: ຕາມໃບ ຫຼື ຕາມສິນຄ້າ" },
      { no: 2, action: "ກັ່ນຕອງຕາມສາງ ແລະ ຈຳນວນວັນທີ່ຄ້າງ" },
      { no: 3, action: "ຈັດການໃບເກົ່າກ່ອນ: ຈ່າຍໃຫ້ຄົບ ຫຼື ປະສານໃຫ້ຍົກເລີກ" },
      { no: 4, action: "ພິມລາຍງານ ຖ້າຕ້ອງໃຊ້ໃນທີ່ປະຊຸມ" },
    ],
    issues: [
      { problem: "ໃບຄ້າງທີ່ຍົກເລີກໄປແລ້ວຍັງຂຶ້ນ", fix: "ໃຫ້ຂາຍຍົກເລີກໃນ ERP — WMS ອ່ານຕາມເອກະສານຕົ້ນທາງ" },
    ],
    forms: ["F-23"],
  },
  {
    code: "WI-RPT-04",
    title: "ວິເຄາະ Aging, Movers ແລະ stock ຂັ້ນຕ່ຳ",
    group: "ລາຍງານ",
    sop: "SOP-WH-10",
    actors: ["manager", "purchasing"],
    screen: { label: "ສິນຄ້າຄ້າງ (Aging)", href: "/movements/aging" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ເປີດ Aging → ເບິ່ງສິນຄ້າທີ່ບໍ່ເຄື່ອນໄຫວດົນ ແລະ ມູນຄ່າທຶນຈົມ" },
      { no: 2, action: "ເປີດ Movers → ເບິ່ງສິນຄ້າຂາຍໄວ ເພື່ອຈັດບ່ອນເກັບໃກ້ທາງອອກ" },
      { no: 3, action: "ເປີດ stock ຂັ້ນຕ່ຳ/ຂັ້ນສູງ → ລາຍການທີ່ຕ້ອງເຕີມ ຫຼື ເກັບເກີນ" },
      { no: 4, action: "ສົ່ງລາຍການໃຫ້ຈັດຊື້/ຂາຍ ດຳເນີນການ" },
    ],
    issues: [
      { problem: "ບໍ່ມີລາຍການເຕືອນເລີຍ", fix: "ອາດຍັງບໍ່ໄດ້ເປີດການຄຸມສາງ ຫຼື ຍັງບໍ່ໄດ້ຕັ້ງຄ່າ min/max (WI-SET-02)" },
    ],
    forms: ["F-21"],
  },
  {
    code: "WI-RPT-05",
    title: "ຄົ້ນປະຫວັດ (Audit) ແລະ export",
    group: "ລາຍງານ",
    sop: "SOP-WH-08",
    actors: ["supervisor", "manager", "accounting"],
    screen: { label: "ປະຫວັດ (Audit)", href: "/movements/ledger" },
    prerequisites: [],
    steps: [
      { no: 1, action: "ກັ່ນຕອງ: ສາງ · ຊ່ວງວັນທີ່ · ປະເພດເອກະສານ · ຄຳຄົ້ນຫາ" },
      { no: 2, action: "ກົດແຖວ ເພື່ອຂະຫຍາຍເບິ່ງລາຍການໃນເອກະສານ" },
      { no: 3, action: "ກົດ CSV ເພື່ອດາວໂຫຼດ ຫຼື ກົດ ພິມ" },
    ],
    issues: [
      { problem: "ເປີດ CSV ໃນ Excel ແລ້ວພາສາລາວເພື້ຽນ", fix: "ນຳເຂົ້າດ້ວຍ encoding UTF-8" },
    ],
    forms: ["F-25"],
  },

  /* ── ຕັ້ງຄ່າ ──────────────────────────────────────────────────── */
  {
    code: "WI-SET-01",
    title: "ຈັດການສິດເຂົ້າເຖິງ",
    group: "ຕັ້ງຄ່າ",
    sop: "SOP-WH-11",
    actors: ["manager"],
    screen: { label: "ຈັດການສິດເຂົ້າເຖິງ", href: "/settings/access" },
    prerequisites: ["ເປັນຜູ້ຈັດການ", "ມີຄຳຂໍທີ່ອະນຸມັດແລ້ວ"],
    steps: [
      { no: 1, action: "ຄົ້ນຫາພະນັກງານ", expect: "ສະແດງສະເພາະຄົນໃນພະແນກສາງ ແລະ ໄອທີ" },
      { no: 2, action: "ເລືອກ role: ຜູ້ຈັດການ · Supervisor · ນາຍສາງ" },
      { no: 3, action: "ຕິກສາງທີ່ຮັບຜິດຊອບ", warn: "Supervisor/ນາຍສາງ ຕ້ອງມີຢ່າງໜ້ອຍ 1 ສາງ ບໍ່ດັ່ງນັ້ນຈະໃຊ້ງານບໍ່ໄດ້" },
      { no: 4, action: "ມອບສິດພິເສດ (ເຊັ່ນ ລົບໃບໂອນ) ເທົ່າທີ່ຈຳເປັນ" },
      { no: 5, action: "ບັນທຶກ ແລະ ແຈ້ງຜູ້ໃຊ້ໃຫ້ເຂົ້າລະບົບໃໝ່" },
    ],
    issues: [
      { problem: "ຜູ້ໃຊ້ຍັງບໍ່ເຫັນສາງ", fix: "ໃຫ້ອອກຈາກລະບົບແລ້ວເຂົ້າໃໝ່ — ສິດອ່ານຕອນເຂົ້າລະບົບ" },
      { problem: "ຫາຄົນບໍ່ພົບ", fix: "ຄົນນອກພະແນກສາງ/ໄອທີ ຈະບໍ່ຂຶ້ນ — ຕ້ອງແກ້ພະແນກໃນລະບົບບຸກຄະລາກອນກ່ອນ" },
    ],
    forms: [],
  },
  {
    code: "WI-SET-02",
    title: "ຕັ້ງຄ່າ stock ຂັ້ນຕ່ຳ / ຂັ້ນສູງ",
    group: "ຕັ້ງຄ່າ",
    sop: "SOP-WH-10",
    actors: ["manager"],
    screen: { label: "ຕັ້ງຄ່າ stock ຂັ້ນຕ່ຳ/ຂັ້ນສູງ", href: "/settings/min-stock" },
    prerequisites: ["ເປັນຜູ້ຈັດການ"],
    steps: [
      { no: 1, action: "ແທັບ ສາງທີ່ຄຸມ → ຕິກເປີດສາງ", warn: "ຄ່າເລີ່ມຕົ້ນປິດໝົດ — ບໍ່ເປີດ = ບໍ່ມີການເຕືອນ" },
      { no: 2, action: "ແທັບ ຄ່າ min/max → ຄົ້ນສິນຄ້າ → ໃສ່ຂັ້ນຕ່ຳ/ຂັ້ນສູງ → ບັນທຶກ" },
      { no: 3, action: "ຫຼື ແທັບ ນຳເຂົ້າ Excel: ດາວໂຫຼດ template (ມີຄ່າປັດຈຸບັນ) → ແກ້ → ອັບກັບ" },
      { no: 4, action: "ກວດຜົນທີ່ badge ໜ້າຫຼັກ ແລະ ລາຍງານ stock ຂັ້ນຕ່ຳ" },
    ],
    issues: [
      { problem: "ຢາກລ້າງຄ່າເກົ່າທັງໝົດ", fix: "ຕິກ ແທນທີ່ທັງໝົດ ຕອນນຳເຂົ້າ Excel" },
      { problem: "ຄົງເຫຼືອບໍ່ຕົງກັບທີ່ຄາດ", fix: "ຄົງເຫຼືອທຽບເປັນຍອດລວມທັງສາງ ບໍ່ແມ່ນຕໍ່ location" },
    ],
    forms: ["F-21"],
  },
  {
    code: "WI-SET-03",
    title: "ຕັ້ງຄ່າສາງ / Rack / Location ແລະ SN ຕໍ່ເມນູ",
    group: "ຕັ້ງຄ່າ",
    sop: "SOP-WH-11",
    actors: ["manager"],
    screen: { label: "ສາງ / Rack / Location", href: "/settings/warehouses" },
    prerequisites: ["ເປັນຜູ້ຈັດການ"],
    steps: [
      { no: 1, action: "ເລືອກສາງ ແລ້ວຂະຫຍາຍເບິ່ງ rack / location" },
      { no: 2, action: "ເພີ່ມ/ແກ້ rack ແລະ location ໃຫ້ຕົງກັບຜັງຈິງ" },
      { no: 3, action: "ຕັ້ງການໃຊ້ SN ຕໍ່ເມນູ (ຮັບ · ຈ່າຍ · ໂອນ · pallet · ປັບປຸງ · ຮັບຄືນ)" },
      { no: 4, action: "ບັນທຶກ ແລ້ວພິມປ້າຍ location ໃໝ່ ຖ້າມີການປ່ຽນ" },
    ],
    issues: [
      { problem: "ປິດ SN ແລ້ວຂໍ້ມູນ serial ຫາຍບໍ", fix: "ບໍ່ຫາຍ — ພຽງແຕ່ບໍ່ບັງຄັບໃຫ້ຍິງໃນເມນູນັ້ນ" },
    ],
    forms: ["F-20"],
  },
  {
    code: "WI-SET-04",
    title: "ກຳນົດສິນຄ້າທີ່ຕ້ອງເກັບ ISN ແລະ ຍີ່ຫໍ້ບັງຄັບ SN",
    group: "ຕັ້ງຄ່າ",
    sop: "SOP-WH-11",
    actors: ["manager"],
    screen: { label: "ສິນຄ້າທີ່ຕ້ອງເກັບ ISN", href: "/settings/isn-scope" },
    prerequisites: ["ເປັນຜູ້ຈັດການ"],
    steps: [
      { no: 1, action: "ເລືອກໝວດສິນຄ້າທີ່ຕ້ອງເກັບ ISN", warn: "ຄຸມດ້ວຍໝວດ ບໍ່ແມ່ນ flag ຂອງແຕ່ລະລາຍການ" },
      { no: 2, action: "ເພີ່ມລາຍການຍົກເວັ້ນ ສຳລັບສິນຄ້າທີ່ບໍ່ຕ້ອງເກັບ" },
      { no: 3, action: "ໄປໜ້າ ຍີ່ຫໍ້ບັງຄັບ SN+ISN ເພື່ອກຳນົດຍີ່ຫໍ້ທີ່ຕ້ອງມີທັງສອງ" },
      { no: 4, action: "ບັນທຶກ ແລ້ວທົດລອງຮັບ 1 ລາຍການ ເພື່ອກວດຜົນ" },
    ],
    issues: [
      { problem: "ລາຍການທີ່ຄວນເກັບ ISN ແຕ່ບໍ່ຖາມ", fix: "ກວດວ່າໝວດຂອງມັນຢູ່ໃນຂອບເຂດ ຫຼື ຢູ່ໃນລາຍການຍົກເວັ້ນ" },
    ],
    forms: [],
  },
  {
    code: "WI-SET-05",
    title: "ຕັ້ງລາຍງານທາງເມວ",
    group: "ຕັ້ງຄ່າ",
    sop: "SOP-WH-11",
    actors: ["manager", "it"],
    screen: { label: "ລາຍງານທາງເມວ", href: "/settings/email-reports" },
    prerequisites: ["ເປັນຜູ້ຈັດການ", "ມີອີເມວຜູ້ຮັບ"],
    steps: [
      { no: 1, action: "ເພີ່ມຜູ້ຮັບ ແລະ ເລືອກສາງທີ່ຈະລວມໃນລາຍງານ" },
      { no: 2, action: "ເລືອກຫົວຂໍ້ທີ່ຕ້ອງການ (ຮັບ/ຈ່າຍ · ຄ້າງຈ່າຍ · stock ຂັ້ນຕ່ຳ …)" },
      { no: 3, action: "ຕັ້ງເວລາສົ່ງ ແລ້ວບັນທຶກ" },
      { no: 4, action: "ກົດສົ່ງທົດລອງ ແລະ ກວດກ່ອງຂາເຂົ້າ" },
    ],
    issues: [
      { problem: "ເມວບໍ່ມາ", fix: "ກວດ spam ກ່ອນ ແລ້ວແຈ້ງໄອທີ ກວດການຕັ້ງຄ່າຜູ້ສົ່ງ" },
    ],
    forms: ["F-22"],
  },
];

export const WI_BY_CODE = new Map(WORK_INSTRUCTIONS.map((w) => [w.code, w]));

/** ໝວດ ຕາມລຳດັບທີ່ຢາກໃຫ້ສະແດງ. */
export const WI_GROUPS: string[] = [
  "ຮັບສິນຄ້າ",
  "ຈັດເກັບ",
  "ຈ່າຍສິນຄ້າ",
  "ໂອນສາງ",
  "ຮັບຄືນ",
  "ກວດນັບ",
  "ປັບປຸງ",
  "ຝາກເຄື່ອງ",
  "ລາຍງານ",
  "ຕັ້ງຄ່າ",
];
