import type { Workflow } from "./types";

/**
 * ຂະບວນການ (Workflow) — ພາບລວມ "ໃຜ ເຮັດຫຍັງ ດ້ວຍໜ້າຈໍໃດ ແລະ ເກີດເອກະສານໃດ"
 * ຕັ້ງແຕ່ຕົ້ນຈົນຈົບ. ລາຍລະອຽດການປະຕິບັດຢູ່ SOP, ວິທີກົດຢູ່ WI.
 */
export const WORKFLOWS: Workflow[] = [
  {
    code: "WF-01",
    name: "ຮັບສິນຄ້າຈາກຜູ້ສະໜອງ",
    tone: "emerald",
    goal: "ສິນຄ້າທີ່ມາຮອດ ຖືກນັບ ຖືກບັນທຶກເຂົ້າ stock ແລະ ຕັ້ງໜີ້ຜູ້ສະໜອງຢ່າງຖືກຕ້ອງ ພາຍໃນມື້ດຽວກັນ.",
    trigger: "ຜູ້ສະໜອງ/ຂົນສົ່ງ ນຳສິນຄ້າມາຮອດສາງ ພ້ອມໃບ packing.",
    scope: "ການຮັບຕາມ PO ທຸກສາງ (ບໍ່ລວມການຮັບໂອນລະຫວ່າງສາງ ແລະ ຮັບຄືນຈາກລູກຄ້າ).",
    owner: "keeper",
    roles: ["purchasing", "receiver", "keeper", "supervisor", "forklift"],
    steps: [
      {
        no: 1,
        role: "purchasing",
        action: "ອອກ PO ແລະ ດຳເນີນການອະນຸມັດ",
        detail: "PO ທີ່ຍັງບໍ່ອະນຸມັດ ລະບົບຈະບລັອກການສ້າງໃບກວດນັບ.",
        form: "F-02",
        control: "PO ຕ້ອງມີສະຖານະ ອະນຸມັດແລ້ວ",
      },
      {
        no: 2,
        role: "receiver",
        action: "ນຳເຂົ້າໃບ packing",
        detail: "ໂຫຼດ template Excel ຕາມ PO ຫຼື ອັບໄຟລ໌ຜູ້ສະໜອງ ແລ້ວຈັບຄູ່ລະຫັດ SML; ແນບ PDF ໄວ້ອ້າງອີງ.",
        screen: { label: "ຮັບສິນຄ້າ › ໃບ packing", href: "/movements/receive" },
        form: "F-01",
      },
      {
        no: 3,
        role: "receiver",
        action: "ກວດລາຍການ ແລະ ສ້າງໃບກວດນັບ",
        detail: "1 ໃບກວດນັບ ອ້າງໄດ້ຫຼາຍ PO ແຕ່ຕ້ອງເປັນສາງດຽວ.",
        screen: { label: "ໃບກວດນັບ", href: "/movements/receive?tab=count" },
        form: "F-03",
        control: "ລາຍການທີ່ບໍ່ຢູ່ໃນ PO / ເກີນຄ້າງຮັບ = ເຕືອນ ຕ້ອງຢືນຢັນກ່ອນ",
      },
      {
        no: 4,
        role: "receiver",
        action: "ນັບຂອງຈິງ ແລະ ບັນທຶກຈຳນວນຮັບ",
        detail: "ນັບຕໍ່ລາຍການ, ກວດສະພາບຫຸ້ມຫໍ່; ສິນຄ້າ serial ຍິງ/ສ້າງ ISN ໃຫ້ຄົບຕາມຈຳນວນ.",
        screen: { label: "ໃບກວດນັບ (ລາຍລະອຽດ)", href: "/movements/receive?tab=count" },
        control: "ຈຳນວນໃນລະບົບ = ຈຳນວນນັບຈິງ ບໍ່ແມ່ນຈຳນວນໃນໃບ packing",
      },
      {
        no: 5,
        role: "keeper",
        action: "Post ໃບກວດນັບ → ຮັບເຂົ້າ WMS",
        detail: "ລະບົບສ້າງໃບຮັບ RC, ເພີ່ມ stock ຢູ່ location ທີ່ເລືອກ ແລະ ບັນທຶກ ISN ເຂົ້າສາງ.",
        screen: { label: "ຮັບສິນຄ້າ", href: "/movements/receive" },
        form: "F-04",
      },
      {
        no: 6,
        role: "keeper",
        action: "ລະບົບຕັ້ງໜີ້ຜູ້ສະໜອງໃນ ERP",
        detail: "ໃບຊື້ຕິດໜີ້ຖືກສ້າງອັດຕະໂນມັດຈາກລາຄາໃນ PO (ເປີດໃຊ້ຕາມການຕັ້ງຄ່າ).",
        form: "F-05",
      },
      {
        no: 7,
        role: "forklift",
        action: "ຈັດເກັບເຂົ້າບ່ອນ (ໄປຕໍ່ WF-02)",
        detail: "ພາຍໃນ 2 ຊົ່ວໂມງຫຼັງຮັບ ບໍ່ໃຫ້ສິນຄ້າຄ້າງຢູ່ພື້ນທີ່ຮັບ.",
        screen: { label: "ບ່ອນວ່າງ (Putaway)", href: "/movements/putaway" },
      },
      {
        no: 8,
        role: "supervisor",
        action: "ກວດຜົນຮັບປະຈຳວັນ",
        detail: "ທຽບໃບຮັບກັບ PO ຄ້າງຮັບ; ລາຍການຮັບບໍ່ຄົບ ແຈ້ງຈັດຊື້.",
        screen: { label: "ເຄື່ອນໄຫວປະຈຳວັນ", href: "/movements/daily" },
      },
    ],
    exceptions: [
      { case: "PO ຍັງບໍ່ອະນຸມັດ", action: "ຢຸດການຮັບ ແຈ້ງຈັດຊື້ໃຫ້ອະນຸມັດກ່ອນ — ຫ້າມຮັບເຂົ້າດ້ວຍວິທີອື່ນ." },
      { case: "ຈຳນວນມາບໍ່ຄົບ", action: "ຮັບຕາມຈິງ, ລະບຸເຫດຜົນ, ສ່ວນທີ່ເຫຼືອຍັງຄ້າງໃນ PO." },
      { case: "ສິນຄ້າເສຍຫາຍ / ຜິດລຸ້ນ", action: "ບໍ່ຮັບເຂົ້າ, ຖ່າຍຮູບ, ແຈ້ງຈັດຊື້ ແລະ ບັນທຶກໃນໝາຍເຫດໃບກວດນັບ." },
      { case: "ສິນຄ້າບໍ່ຢູ່ໃນ PO ໃດເລີຍ", action: "ແຍກໄວ້ຕ່າງຫາກ ຫ້າມຮັບ ຈົນກວ່າຈັດຊື້ຢືນຢັນ." },
      { case: "ISN ຊໍ້າກັບຂອງເກົ່າ", action: "ຢຸດ ແລະ ກວດວ່າສິນຄ້າຖືກຈ່າຍອອກແທ້ບໍ ກ່ອນສ້າງ ISN ໃໝ່." },
    ],
    outputs: ["stock ເພີ່ມທີ່ location", "ISN ຢູ່ໃນສາງ", "ໃບຊື້ຕິດໜີ້ (ຕັ້ງໜີ້)"],
    sops: ["SOP-WH-01"],
    wis: ["WI-RCV-01", "WI-RCV-02", "WI-RCV-03", "WI-RCV-04"],
    forms: ["F-01", "F-02", "F-03", "F-04", "F-05"],
    kpis: [
      { name: "ຮັບເຂົ້າລະບົບໃນມື້ທີ່ມາຮອດ", target: "100%" },
      { name: "ຄວາມຖືກຕ້ອງຈຳນວນຮັບ", target: "≥ 99.5%" },
    ],
  },
  {
    code: "WF-02",
    name: "ຈັດເກັບເຂົ້າບ່ອນ (Putaway & Pallet)",
    tone: "aqua",
    goal: "ທຸກສິນຄ້າມີບ່ອນເກັບທີ່ຮູ້ແນ່ນອນ ແລະ ຄົ້ນຫາໄດ້ໄວ.",
    trigger: "ຮັບສິນຄ້າເຂົ້າແລ້ວ ຫຼື ຕ້ອງຈັດພື້ນທີ່ໃໝ່.",
    scope: "ການວາງ pallet, ຍ້າຍ pallet, ຈັດ location ພາຍໃນ ແລະ ຂ້າມສາງ.",
    owner: "forklift",
    roles: ["keeper", "forklift", "supervisor"],
    steps: [
      {
        no: 1,
        role: "keeper",
        action: "ພິມປ້າຍ pallet / location",
        detail: "ປ້າຍ barcode (Code 128) ຕິດໃສ່ pallet ຈິງ ແລະ ໜ້າ rack.",
        screen: { label: "ພິມ Label/Barcode", href: "/movements/labels" },
        form: "F-20",
      },
      {
        no: 2,
        role: "forklift",
        action: "ຫາບ່ອນວ່າງທີ່ເໝາະສົມ",
        detail: "ເບິ່ງ % ການໃຊ້ພື້ນທີ່ ແລະ ເລືອກ location ວ່າງ/ໃຊ້ໜ້ອຍ ຕາມນ້ຳໜັກ-ຂະໜາດ.",
        screen: { label: "ບ່ອນວ່າງ (Putaway)", href: "/movements/putaway" },
      },
      {
        no: 3,
        role: "keeper",
        action: "ປະກອບ pallet",
        detail: "ເລືອກ pallet → ຍິງສິນຄ້າ/ISN ເຂົ້າ → ບັນທຶກ; stock ຈະໄປຢູ່ບ່ອນຂອງ pallet.",
        screen: { label: "ປະກອບ Pallet", href: "/movements/pallet-load" },
        form: "F-17",
      },
      {
        no: 4,
        role: "forklift",
        action: "ຍ້າຍ pallet ໄປ location ຈິງ",
        detail: "ບັນທຶກທຸກຄັ້ງທີ່ຍ້າຍ — ສິນຄ້າ ແລະ serial ເທິງ pallet ຍ້າຍຕາມ (ຂ້າມສາງໄດ້).",
        screen: { label: "ຍ້າຍ Pallet", href: "/movements/pallet-move" },
        form: "F-15",
        control: "ປ້າຍ location ຈິງ ຕ້ອງຕົງກັບ location ໃນລະບົບ",
      },
      {
        no: 5,
        role: "supervisor",
        action: "ກວດຄວາມເປັນລະບຽບ ແລະ ຄວາມຈຸ",
        screen: { label: "ແຜນຜັງ Rack", href: "/rack-visualization" },
      },
    ],
    exceptions: [
      { case: "location ເຕັມ", action: "ຫາບ່ອນອື່ນຜ່ານໜ້າ Putaway; ຖ້າ rack ເຕັມທັງໝົດ ແຈ້ງ Supervisor ຈັດພື້ນທີ່." },
      { case: "ປ້າຍ barcode ອ່ານບໍ່ໄດ້", action: "ພິມປ້າຍໃໝ່ທັນທີ ຫ້າມຂຽນມືທົດແທນ." },
      { case: "ຍ້າຍແລ້ວລືມບັນທຶກ", action: "ບັນທຶກຍ້ອນຫຼັງທັນທີທີ່ຮູ້ ແລະ ແຈ້ງ Supervisor ເພື່ອກວດ SN ທຽບ stock." },
    ],
    outputs: ["location ຂອງສິນຄ້າຖືກຕ້ອງ", "ໃບຍ້າຍ pallet (PMV)"],
    sops: ["SOP-WH-02"],
    wis: ["WI-PUT-01", "WI-PUT-02", "WI-PUT-03", "WI-PUT-04"],
    forms: ["F-15", "F-17", "F-20"],
    kpis: [
      { name: "ຈັດເກັບພາຍໃນ 2 ຊົ່ວໂມງ", target: "≥ 95%" },
      { name: "ຄວາມແມ່ນຍຳ location", target: "≥ 99%" },
    ],
  },
  {
    code: "WF-03",
    name: "ຈ່າຍສິນຄ້າອອກສາງ",
    tone: "red",
    goal: "ຈ່າຍສິນຄ້າຖືກລາຍການ ຖືກຈຳນວນ ຖືກ ISN ພ້ອມຫຼັກຖານຄົບ ແລະ ຕັດຍອດທັນທີ.",
    trigger: "ມີ ໃບຂໍເບີກ (122) · ບິນຂາຍ (44) · ຫຼື ໃບຂໍໂອນທີ່ອະນຸມັດແລ້ວ (124).",
    scope: "ການຈ່າຍອອກຈາກສາງທຸກປະເພດ ຍົກເວັ້ນການຈັດຖ້ຽວຂົນສົ່ງ (ເບິ່ງ WF-04).",
    owner: "keeper",
    roles: ["sales", "supervisor", "keeper", "picker", "driver"],
    steps: [
      {
        no: 1,
        role: "sales",
        action: "ອອກເອກະສານຕົ້ນທາງໃນ ERP",
        detail: "ບິນຂາຍ / ໃບຂໍເບີກ ຕ້ອງລະບຸສາງໃຫ້ຖືກ.",
        form: "F-06",
      },
      {
        no: 2,
        role: "keeper",
        action: "ເລືອກເອກະສານ ແລະ ຈັດສັນ location",
        detail: "ລະບົບສະແດງຍອດຄ້າງຈ່າຍ; ເລືອກ location ຕາມ FEFO (⭐ = ຄວນເກັບກ່ອນ) ແລະ ໃສ່ຈຳນວນ.",
        screen: { label: "ຈ່າຍສິນຄ້າ › ສ້າງໃບ pick", href: "/movements/issue" },
        form: "F-09",
        control: "ຈຳນວນຕ້ອງບໍ່ເກີນຍອດຄ້າງຈ່າຍ ແລະ ບໍ່ເກີນຍອດຂອງ location",
      },
      {
        no: 3,
        role: "picker",
        action: "ພິມໃບເກັບສິນຄ້າ ແລ້ວຍ່າງເກັບ",
        detail: "ໃບຈັດລຳດັບຕາມ location ໃຫ້ຍ່າງຮອບດຽວ.",
        screen: { label: "ໃບເກັບສິນຄ້າ", href: "/movements/pick" },
        form: "F-13",
      },
      {
        no: 4,
        role: "picker",
        action: "ຢືນຢັນຈ່າຍ ໂດຍຍິງ ISN ທຸກໜ່ວຍ",
        detail: "ຍິງບໍ່ຄົບ ລະບົບຈະບໍ່ໃຫ້ຢືນຢັນ.",
        screen: { label: "ຈ່າຍສິນຄ້າ › ຢືນຢັນຈ່າຍ", href: "/movements/issue?tab=pending" },
        control: "ທຸກ ISN ທີ່ຈັດສັນໄວ້ ຕ້ອງຖືກຍິງ",
      },
      {
        no: 5,
        role: "keeper",
        action: "ລະບົບຕັດ stock ແລະ ອອກເອກະສານ",
        detail: "ສ້າງໃບຈ່າຍ DP, ປ່ຽນສະຖານະ ISN ເປັນຈ່າຍອອກ ແລະ ອອກເອກະສານ ERP ຕາມປະເພດຕົ້ນທາງ.",
        form: "F-10",
      },
      {
        no: 6,
        role: "keeper",
        action: "ພິມໃບຈ່າຍ ໃຫ້ຜູ້ຮັບລົງລາຍເຊັນ",
        screen: { label: "ປະຫວັດການຈ່າຍ", href: "/movements/issue?tab=history" },
        form: "F-11",
      },
      {
        no: 7,
        role: "supervisor",
        action: "ຕິດຕາມຍອດຄ້າງຈ່າຍ",
        detail: "ໃບທີ່ຈ່າຍບໍ່ຄົບຈະຄ້າງຢູ່ລາຍງານ ຈົນກວ່າຈະຈ່າຍໝົດ ຫຼື ຍົກເລີກ.",
        screen: { label: "ຄ້າງຈ່າຍອອກສາງ", href: "/movements/pending-out" },
      },
    ],
    exceptions: [
      { case: "ຂອງບໍ່ພໍ", action: "ຈ່າຍບາງສ່ວນ (ທະຍອຍ) ພ້ອມລະບຸເຫດຜົນ; ສ່ວນທີ່ເຫຼືອຍັງຄ້າງໃນເອກະສານຕົ້ນທາງ." },
      { case: "ISN ຍິງແລ້ວບໍ່ຢູ່ໃນລາຍການຈັດສັນ", action: "ກວດວ່າຂອງມາຈາກ location ອື່ນບໍ — ຖ້າແມ່ນ ໃຫ້ແກ້ການຈັດສັນ ບໍ່ແມ່ນຍິງຂ້າມ." },
      { case: "ຈ່າຍຜິດ ຫຼັງຢືນຢັນແລ້ວ", action: "ຂໍ Supervisor/ຜູ້ຈັດການ ລົບໃບຈ່າຍ (ຄືນ stock + ຍົກເລີກເອກະສານ ERP) ແລ້ວເຮັດໃໝ່." },
      { case: "ບໍ່ມີເອກະສານຕົ້ນທາງ", action: "ບໍ່ຈ່າຍ — ໃຫ້ຝ່າຍທີ່ຂໍ ອອກໃບຂໍເບີກກ່ອນ." },
    ],
    outputs: ["stock ຫຼຸດ", "ISN ປ່ຽນເປັນຈ່າຍອອກ", "ໃບຈ່າຍ DP + ເອກະສານ ERP"],
    sops: ["SOP-WH-03"],
    wis: ["WI-ISS-01", "WI-ISS-02", "WI-ISS-03", "WI-ISS-04", "WI-ISS-06"],
    forms: ["F-06", "F-07", "F-09", "F-10", "F-11", "F-13"],
    kpis: [
      { name: "ຄວາມຖືກຕ້ອງການຈ່າຍ", target: "≥ 99.5%" },
      { name: "ໃບ pick ຄ້າງຢືນຢັນຂ້າມມື້", target: "0" },
    ],
  },
  {
    code: "WF-04",
    name: "ຈັດຖ້ຽວຂົນສົ່ງ (Trip Pick)",
    tone: "amber",
    goal: "ຈັດສິນຄ້າຂອງທຸກບິນໃນຖ້ຽວດຽວກັນ ຄັ້ງດຽວ ຂຶ້ນລົດຖືກຄົບ.",
    trigger: "ຂົນສົ່ງສ້າງຖ້ຽວ (TMS) ທີ່ຍັງບໍ່ທັນເລີ່ມຈັດສົ່ງ.",
    scope: "ບິນຂາຍທີ່ຖືກຈັດເຂົ້າຖ້ຽວ — 1 ຖ້ຽວ = 1 ໃບສັ່ງຈ່າຍ ແຕ່ບິນຢູ່ລະດັບແຖວ.",
    owner: "keeper",
    roles: ["keeper", "picker", "supervisor", "driver"],
    steps: [
      {
        no: 1,
        role: "keeper",
        action: "ດຶງຖ້ຽວມາເປັນໃບສັ່ງຈ່າຍ",
        detail: "ເລືອກຖ້ຽວທີ່ຍັງບໍ່ເລີ່ມຈັດສົ່ງ; ຍອດຕໍ່ບິນ = ຈຳນວນທີ່ຂຶ້ນລົດຖ້ຽວນີ້ ຫຼື ຍອດຄ້າງຈ່າຍ (ອັນໃດໜ້ອຍກວ່າ).",
        screen: { label: "ຈ່າຍສິນຄ້າ › ໃບຈັດຖ້ຽວ", href: "/movements/issue" },
        form: "F-12",
      },
      {
        no: 2,
        role: "picker",
        action: "ພິມໃບຈັດຖ້ຽວ ແລ້ວເກັບຕາມບ່ອນເກັບ",
        detail: "ໃບພິມລວມແຖວທີ່ສິນຄ້າ+ບ່ອນເກັບດຽວກັນ ແລະ ຮຽງຕາມເສັ້ນທາງເກັບ.",
        form: "F-12",
      },
      {
        no: 3,
        role: "picker",
        action: "ຢືນຢັນຈ່າຍ (ຍິງ ISN)",
        detail: "ລະບົບແຍກອອກເປັນໃບຈ່າຍຕໍ່ບິນ ໃຫ້ອັດຕະໂນມັດ.",
        screen: { label: "ຢືນຢັນຈ່າຍ", href: "/movements/issue?tab=pending" },
        control: "ຈຳນວນລວມຕໍ່ບິນ ຕ້ອງບໍ່ເກີນຄ້າງຈ່າຍຂອງບິນນັ້ນ",
      },
      {
        no: 4,
        role: "driver",
        action: "ກວດຮັບເຄື່ອງ ແລະ ລົງລາຍເຊັນ",
        detail: "ໃບຈັດຖ້ຽວມີຊ່ອງລາຍເຊັນ: ຜູ້ເກັບ · ຜູ້ຈ່າຍເຄື່ອງອອກສາງ · ຜູ້ກວດສອບ · ຄົນຂັບ.",
        form: "F-12",
      },
      {
        no: 5,
        role: "supervisor",
        action: "ກວດວ່າຖ້ຽວອອກຄົບ ແລະ ບໍ່ມີບິນຄ້າງ",
        screen: { label: "ຄ້າງຈ່າຍອອກສາງ", href: "/movements/pending-out" },
      },
    ],
    exceptions: [
      { case: "1 ບິນ ແບ່ງຫຼາຍຖ້ຽວ", action: "ຖືກຕ້ອງຕາມລະບົບ — ຈ່າຍຕາມຈຳນວນຂອງແຕ່ລະຖ້ຽວ ສ່ວນທີ່ເຫຼືອຄ້າງໄວ້." },
      { case: "ຖ້ຽວເລີ່ມຈັດສົ່ງແລ້ວ", action: "ຈະບໍ່ຂຶ້ນໃນລາຍການເລີ່ມຕົ້ນ — ໃຫ້ປັບຕົວກັ່ນຕອງ ຫຼື ຕິດຕໍ່ຂົນສົ່ງ." },
      { case: "ຂອງບໍ່ພໍໃນຖ້ຽວ", action: "ຫຼຸດຈຳນວນຂອງແຖວນັ້ນ ພ້ອມແຈ້ງຂາຍ/ຂົນສົ່ງ ກ່ອນລົດອອກ." },
    ],
    outputs: ["ໃບຈ່າຍ DP ຕໍ່ບິນ", "ໃບຈັດຖ້ຽວທີ່ເຊັນຮັບແລ້ວ"],
    sops: ["SOP-WH-04"],
    wis: ["WI-ISS-05"],
    forms: ["F-07", "F-12"],
    kpis: [
      { name: "ຖ້ຽວອອກທັນເວລານັດ", target: "≥ 95%" },
      { name: "ຂຶ້ນເຄື່ອງຜິດບິນ", target: "0" },
    ],
  },
  {
    code: "WF-05",
    name: "ໂອນສິນຄ້າລະຫວ່າງສາງ",
    tone: "brand",
    goal: "ສິນຄ້າຍ້າຍລະຫວ່າງສາງໂດຍມີການອະນຸມັດ ແລະ ຕິດຕາມໄດ້ທຸກຂັ້ນ ບໍ່ມີຂອງຫາຍລະຫວ່າງທາງ.",
    trigger: "ສາງປາຍທາງຕ້ອງການສິນຄ້າຈາກສາງອື່ນ.",
    scope: "ໃບຂໍໂອນ (124) — ຂໍ → ອະນຸມັດ → ຈ່າຍ → ຮັບ → ຮັບຄືນສ່ວນຄ້າງ.",
    owner: "supervisor",
    roles: ["keeper", "manager", "supervisor", "driver"],
    steps: [
      {
        no: 1,
        role: "keeper",
        action: "ສາງປາຍທາງ ອອກໃບຂໍໂອນ",
        detail: "ລະບຸສາງຕົ້ນທາງ, ລາຍການ, ຈຳນວນ ແລະ ສະພາບສິນຄ້າຕໍ່ແຖວ.",
        screen: { label: "ອອກໃບຂໍໂອນ", href: "/movements/transfer-request" },
        form: "F-08",
      },
      {
        no: 2,
        role: "manager",
        action: "ສາງຕົ້ນທາງ ອະນຸມັດ / ປະຕິເສດ",
        detail: "ສະເພາະໃບທີ່ອະນຸມັດແລ້ວຈຶ່ງຈ່າຍອອກໄດ້; ແກ້ໄຂໃບ = ກັບໄປລໍຖ້າອະນຸມັດໃໝ່.",
        screen: { label: "ອະນຸມັດ ໃບຂໍໂອນ", href: "/movements/transfer-approve" },
        control: "ກວດຄວາມຈຳເປັນ ແລະ ຄົງເຫຼືອຂອງສາງຕົ້ນທາງກ່ອນອະນຸມັດ",
      },
      {
        no: 3,
        role: "keeper",
        action: "ສາງຕົ້ນທາງ ຈ່າຍອອກ → ສາງລະຫວ່າງທາງ (9903)",
        detail: "ຂອງ ແລະ serial ຍ້າຍໄປພັກຢູ່ສາງລະຫວ່າງທາງ ບໍ່ແມ່ນຈ່າຍຂາດ.",
        screen: { label: "ຈ່າຍສິນຄ້າ (ໃບຂໍໂອນ)", href: "/movements/issue" },
        form: "F-10",
      },
      {
        no: 4,
        role: "driver",
        action: "ຂົນສົ່ງລະຫວ່າງສາງ",
        detail: "ຖືເອກະສານໄປພ້ອມ ແລະ ສົ່ງມອບໃຫ້ສາງປາຍທາງ.",
      },
      {
        no: 5,
        role: "keeper",
        action: "ສາງປາຍທາງ ຮັບເຂົ້າຕາມຈິງ",
        detail: "ຮັບບໍ່ຄົບໄດ້ — ສ່ວນທີ່ເຫຼືອຍັງຄ້າງຢູ່ສາງລະຫວ່າງທາງ.",
        screen: { label: "ຮັບໂອນເຂົ້າສາງ", href: "/movements/transfer-receive" },
        control: "ນັບຂອງຈິງກ່ອນຮັບ ແລະ ຍິງ ISN ໃຫ້ຄົບ",
      },
      {
        no: 6,
        role: "keeper",
        action: "ສາງຕົ້ນທາງ ດຶງສ່ວນຄ້າງກັບຄືນ",
        detail: "ໃຊ້ເມື່ອປາຍທາງບໍ່ຮັບ ຫຼື ຮັບບໍ່ຄົບ ເພື່ອບໍ່ໃຫ້ຂອງຄ້າງລະຫວ່າງທາງ.",
        screen: { label: "ຮັບຄືນຈາກການຈ່າຍ", href: "/movements/transfer-return" },
      },
      {
        no: 7,
        role: "supervisor",
        action: "ຕິດຕາມ dashboard ໃຫ້ບໍ່ມີໃບເກີນກຳນົດ",
        screen: { label: "ພາບລວມ ການໂອນ", href: "/movements/transfer-dashboard" },
      },
    ],
    exceptions: [
      { case: "ຂອງຄ້າງລະຫວ່າງທາງດົນ", action: "ຕິດຕາມກັບຂົນສົ່ງ; ຖ້າຂອງກັບຄືນ ໃຫ້ເຮັດ ຮັບຄືນຈາກການຈ່າຍ ທັນທີ." },
      { case: "ຮັບໄດ້ຫຼາຍກວ່າທີ່ຈ່າຍ", action: "ຮັບບໍ່ໄດ້ — ກວດການນັບຂອງທັງສອງສາງ ແລ້ວແກ້ດ້ວຍໃບປັບປຸງ ຖ້າຈຳເປັນ." },
      { case: "ຕ້ອງຍົກເລີກໃບຂໍ", action: "ຍົກເລີກໄດ້ສະເພາະໃບທີ່ຍັງບໍ່ມີການເຄື່ອນໄຫວ." },
    ],
    outputs: ["stock ຍ້າຍລະຫວ່າງສາງ", "ໃບໂອນ ERP", "ຍອດຄ້າງລະຫວ່າງທາງ = 0"],
    sops: ["SOP-WH-05"],
    wis: ["WI-TRF-01", "WI-TRF-02", "WI-TRF-03", "WI-TRF-04", "WI-TRF-05"],
    forms: ["F-08", "F-10", "F-24"],
    kpis: [
      { name: "ໃບຄ້າງອະນຸມັດ", target: "0 ໃບ ເກີນ 1 ວັນ" },
      { name: "ຂອງຄ້າງລະຫວ່າງທາງ", target: "≤ 3 ວັນ" },
    ],
  },
  {
    code: "WF-06",
    name: "ຮັບຄືນຈາກລູກຄ້າ (Sale Return)",
    tone: "aqua",
    goal: "ສິນຄ້າທີ່ລູກຄ້າສົ່ງຄືນ ກັບເຂົ້າ stock ຖືກຕ້ອງ ພ້ອມເອກະສານທາງການເງິນ.",
    trigger: "ລູກຄ້າສົ່ງສິນຄ້າຄືນ ພ້ອມບິນຂາຍອ້າງອີງ.",
    scope: "ການຮັບຄືນເຂົ້າ stock ໃນ WMS (ໃບຫຼຸດໜີ້ເຮັດໃນ SmartBiz).",
    owner: "receiver",
    roles: ["sales", "receiver", "supervisor", "accounting"],
    steps: [
      {
        no: 1,
        role: "sales",
        action: "ອະນຸມັດການຮັບຄືນ ແລະ ແຈ້ງສາງ",
        detail: "ລະບຸບິນຂາຍຕົ້ນທາງ ແລະ ເຫດຜົນການຄືນ.",
      },
      {
        no: 2,
        role: "receiver",
        action: "ກວດສະພາບສິນຄ້າທີ່ຄືນ",
        detail: "ຂອງດີ = ຄືນເຂົ້າ stock ຂາຍໄດ້; ຂອງເສຍ = ແຍກເກັບ ແລະ ແຈ້ງ Supervisor.",
        control: "ຖ່າຍຮູບສະພາບກ່ອນຮັບ ຖ້າມີຮ່ອງຮອຍເສຍຫາຍ",
      },
      {
        no: 3,
        role: "receiver",
        action: "ບັນທຶກຮັບຄືນເຂົ້າ WMS",
        detail: "ເລືອກບິນຂາຍ, ໃສ່ຈຳນວນ, ຍິງ ISN ຄືນ; stock ເພີ່ມ ແລະ serial ກັບເປັນ ຄົງເຫຼືອ.",
        screen: { label: "ຮັບຄືນຈາກລູກຄ້າ", href: "/movements/sale-return" },
        form: "F-14",
      },
      {
        no: 4,
        role: "accounting",
        action: "ອອກໃບຫຼຸດໜີ້ (CN) ໃນ SmartBiz",
        detail: "WMS ບໍ່ອອກ CN ໃຫ້ — ຕ້ອງເຮັດຢູ່ ERP ເພື່ອໃຫ້ບັນຊີຕົງ.",
      },
      {
        no: 5,
        role: "supervisor",
        action: "ກວດ ແລະ ຈັດເກັບຄືນບ່ອນ",
        screen: { label: "ປະຫວັດ (Audit)", href: "/movements/ledger" },
      },
    ],
    exceptions: [
      { case: "ບໍ່ມີບິນຂາຍອ້າງອີງ", action: "ບໍ່ຮັບຄືນ — ໃຫ້ຂາຍຫາບິນຕົ້ນທາງກ່ອນ." },
      { case: "ISN ບໍ່ຕົງກັບທີ່ຈ່າຍອອກ", action: "ຢຸດ ແລະ ກວດກັບຂາຍ — ອາດເປັນເຄື່ອງຄົນລະໜ່ວຍ." },
      { case: "ສິນຄ້າເສຍຫາຍ", action: "ຮັບເຂົ້າແຍກເປັນຂອງເສຍ ແລະ ບໍ່ນຳໄປຂາຍ ຈົນກວ່າຈະຕັດສິນໃຈ." },
    ],
    outputs: ["stock ເພີ່ມ", "serial ກັບເປັນຄົງເຫຼືອ", "ໃບຫຼຸດໜີ້ (ERP)"],
    sops: ["SOP-WH-06"],
    wis: ["WI-RET-01"],
    forms: ["F-07", "F-14"],
    kpis: [{ name: "ບັນທຶກຮັບຄືນພາຍໃນມື້", target: "100%" }],
  },
  {
    code: "WF-07",
    name: "ກວດນັບສິນຄ້າ (Stocktake)",
    tone: "navy",
    goal: "ຢືນຢັນວ່າຍອດໃນລະບົບ = ຂອງຈິງ ແລະ ແກ້ຄວາມຕ່າງດ້ວຍການອະນຸມັດ.",
    trigger: "ຮອບນັບຕາມແຜນ (ປະຈຳເດືອນ/cycle count) ຫຼື ເມື່ອສົງໄສ.",
    scope: "ນັບຕາມສາງ/location — ນັບແບບປິດຕາ (blind) ຫຼື ເປີດຍອດ.",
    owner: "supervisor",
    roles: ["supervisor", "counter", "manager", "accounting"],
    steps: [
      {
        no: 1,
        role: "supervisor",
        action: "ສ້າງຮອບກວດນັບ",
        detail: "ເລືອກສາງ, ວັນນັບ, ຂອບເຂດ ແລະ ຮູບແບບ (blind = ບໍ່ເຫັນຍອດລະບົບ).",
        screen: { label: "ສ້າງຮອບໃໝ່", href: "/stocktake/new" },
        form: "F-18",
      },
      {
        no: 2,
        role: "counter",
        action: "ນັບຂອງຈິງ ແລະ ບັນທຶກ",
        detail: "ນັບຕາມ location; ສິນຄ້າ serial ຍິງ ISN.",
        screen: { label: "ຮອບກວດນັບ", href: "/stocktake" },
        control: "ຢຸດການເຄື່ອນໄຫວຂອງ location ໃນຂະນະນັບ",
      },
      {
        no: 3,
        role: "counter",
        action: "ນັບຊ້ຳລາຍການທີ່ຕ່າງ",
        detail: "ຄວາມຕ່າງທຸກລາຍການຕ້ອງຜ່ານການນັບຊ້ຳ ກ່ອນສົ່ງອະນຸມັດ.",
      },
      {
        no: 4,
        role: "supervisor",
        action: "ສົ່ງຮອບເພື່ອຂໍອະນຸມັດ",
        detail: "ສະຖານະປ່ຽນເປັນ ລໍຖ້າອະນຸມັດ ແລະ ແກ້ໄຂບໍ່ໄດ້ອີກ.",
        screen: { label: "ຮອບກວດນັບ", href: "/stocktake" },
      },
      {
        no: 5,
        role: "manager",
        action: "ອະນຸມັດ ແລະ ປິດຮອບ",
        detail: "ອະນຸມັດແລ້ວ ຄວາມຕ່າງຈຶ່ງຖືກປັບເຂົ້າ stock.",
        control: "ຄວາມຕ່າງມູນຄ່າສູງ ຕ້ອງມີຄຳອະທິບາຍ",
      },
      {
        no: 6,
        role: "accounting",
        action: "ຮັບຜົນນັບໄປກະທົບຍອດບັນຊີ",
        screen: { label: "ຄວາມຖືກຕ້ອງ stock", href: "/movements/accuracy" },
      },
    ],
    exceptions: [
      { case: "ນັບໄດ້ໜ້ອຍກວ່າລະບົບ", action: "ຄົ້ນຫາຢູ່ location ໃກ້ຄຽງ ແລະ ກວດເອກະສານຈ່າຍລ່າສຸດ ກ່ອນສະຫຼຸບວ່າຂາດ." },
      { case: "ນັບໄດ້ຫຼາຍກວ່າລະບົບ", action: "ກວດວ່າມີການຮັບທີ່ຍັງບໍ່ບັນທຶກບໍ ກ່ອນປັບເພີ່ມ." },
      { case: "ຄວາມຕ່າງເກີດຊໍ້າບ່ອນເກົ່າ", action: "ເປີດການສືບສວນ ແລະ ທົບທວນສິດເຂົ້າເຖິງ location ນັ້ນ." },
    ],
    outputs: ["ຮອບນັບປິດແລ້ວ", "ໃບປັບປຸງ stock ຈາກຜົນນັບ", "ບົດລາຍງານຄວາມຕ່າງ"],
    sops: ["SOP-WH-07"],
    wis: ["WI-CNT-01", "WI-CNT-02"],
    forms: ["F-18", "F-17"],
    kpis: [
      { name: "ຄວາມແມ່ນຍຳຫຼັງນັບ", target: "≥ 99%" },
      { name: "ຮອບນັບຕາມແຜນ", target: "100%" },
    ],
  },
  {
    code: "WF-08",
    name: "ປັບປຸງ stock ແລະ ແກ້ຄວາມຕ່າງ",
    tone: "amber",
    goal: "ຄວາມຕ່າງລະຫວ່າງ WMS · ERP · SN ຖືກແກ້ໃຫ້ຕົງ ພ້ອມຫຼັກຖານ ແລະ ການອະນຸມັດ.",
    trigger: "ພົບຄວາມຕ່າງຈາກການນັບ, badge ສຸຂະພາບ ຫຼື ລາຍງານຄວາມຖືກຕ້ອງ.",
    scope: "ການປັບຍອດ, ການຍ້າຍ serial ໃຫ້ຕົງ location ແລະ ການແກ້ຂໍ້ມູນທີ່ບໍ່ກົງ.",
    owner: "manager",
    roles: ["keeper", "supervisor", "manager"],
    steps: [
      {
        no: 1,
        role: "keeper",
        action: "ຢືນຢັນຄວາມຕ່າງດ້ວຍການນັບຊ້ຳ",
        detail: "ຫ້າມປັບຍອດຈາກໜ້າຈໍຢ່າງດຽວ.",
        screen: { label: "ຄວາມຖືກຕ້ອງ stock", href: "/movements/accuracy" },
      },
      {
        no: 2,
        role: "keeper",
        action: "ກວດ SN ທຽບ stock",
        detail: "ຖ້າຈຳນວນຖືກແຕ່ location ຂອງ serial ບໍ່ຕົງ → ຍ້າຍ SN ໃຫ້ຕົງກັບ WMS (ບໍ່ຕ້ອງປັບຍອດ).",
        screen: { label: "ກວດ SN vs Stock", href: "/movements/sn-check" },
        form: "F-16",
      },
      {
        no: 3,
        role: "supervisor",
        action: "ພິສູດເຫດຜົນ ແລະ ຂໍອະນຸມັດ",
        detail: "ລະບຸສາເຫດ: ນັບຜິດ · ບໍ່ໄດ້ບັນທຶກ · ເສຍຫາຍ · ຫາຍ.",
        control: "ຕ້ອງມີເຫດຜົນທຸກໃບ",
      },
      {
        no: 4,
        role: "manager",
        action: "ອະນຸມັດການປັບປຸງ",
        detail: "ຄວາມຕ່າງເກີນເກນທີ່ກຳນົດ ຕ້ອງໄດ້ຮັບການອະນຸມັດກ່ອນ.",
      },
      {
        no: 5,
        role: "keeper",
        action: "ບັນທຶກໃບປັບປຸງ stock",
        screen: { label: "ປັບປຸງ stock", href: "/movements/adjust" },
        form: "F-17",
      },
      {
        no: 6,
        role: "supervisor",
        action: "ກວດຫຼັກຖານໃນປະຫວັດ",
        screen: { label: "ປະຫວັດ (Audit)", href: "/movements/ledger" },
      },
    ],
    exceptions: [
      { case: "ERP ຕ່າງກັບ WMS ແຕ່ຂອງຈິງຖືກ", action: "ຫາເອກະສານທີ່ຂາດ (ຮັບ/ຈ່າຍ ທີ່ບໍ່ໄດ້ບັນທຶກ) ແລ້ວແກ້ດ້ວຍເອກະສານ ບໍ່ແມ່ນປັບຍອດ." },
      { case: "serial ຢູ່ຄົນລະ location", action: "ໃຊ້ ກວດ SN vs Stock ປັບໃຫ້ຕົງ (ຖື location ຂອງ WMS ເປັນຫຼັກ)." },
      { case: "ປັບຜິດ", action: "ຍົກເລີກ/ລົບໃບປັບປຸງ ພາຍໃນວັນດຽວກັນ ແລະ ບັນທຶກໃໝ່ໃຫ້ຖືກ." },
    ],
    outputs: ["ຍອດ WMS = ຂອງຈິງ", "ໃບປັບປຸງພ້ອມເຫດຜົນ", "serial ຢູ່ location ຖືກ"],
    sops: ["SOP-WH-08"],
    wis: ["WI-ADJ-01", "WI-ADJ-02", "WI-ADJ-03"],
    forms: ["F-16", "F-17"],
    kpis: [
      { name: "ໃບປັບປຸງທີ່ບໍ່ມີເຫດຜົນ", target: "0" },
      { name: "ຄວາມຕ່າງທີ່ຄ້າງເກີນ 7 ວັນ", target: "0" },
    ],
  },
  {
    code: "WF-09",
    name: "ຮັບຝາກເຄື່ອງ (Deposit)",
    tone: "brand",
    goal: "ຮັບຝາກ, ຄິດຄ່າຝາກ ແລະ ຄືນເຄື່ອງໃຫ້ຖືກຄົນ ຖືກຈຳນວນ ຖືກຄ່າ.",
    trigger: "ລູກຄ້າ/ໜ່ວຍງານ ນຳເຄື່ອງມາຝາກໄວ້ໃນສາງ.",
    scope: "ເຄື່ອງຝາກທີ່ບໍ່ແມ່ນ stock ຂອງບໍລິສັດ — ຄິດຄ່າຝາກເປັນ THB ຕາມຂັ້ນວັນ.",
    owner: "keeper",
    roles: ["keeper", "supervisor", "manager", "accounting"],
    steps: [
      {
        no: 1,
        role: "keeper",
        action: "ບັນທຶກຮັບຝາກໃໝ່",
        detail: "ຂໍ້ມູນຜູ້ຝາກ, ລາຍການ, ຈຳນວນ, ວັນທີ່ຝາກ ແລະ ບ່ອນເກັບ.",
        screen: { label: "ຮັບຝາກໃໝ່", href: "/deposits/new" },
        form: "F-19",
      },
      {
        no: 2,
        role: "keeper",
        action: "ພິມໃບຮັບຝາກໃຫ້ຜູ້ຝາກເຊັນ",
        screen: { label: "ລາຍການຝາກ", href: "/deposits" },
        form: "F-19",
      },
      {
        no: 3,
        role: "supervisor",
        action: "ຕິດຕາມວັນຝາກ",
        detail: "ເກີນມື້ຟຣີ ຈະຂຶ້ນເປັນສີແດງ — ແຈ້ງຜູ້ຝາກກ່ອນຄ່າຝາກຂຶ້ນຂັ້ນຕໍ່ໄປ.",
        screen: { label: "ລາຍການຝາກ", href: "/deposits" },
      },
      {
        no: 4,
        role: "keeper",
        action: "ຄືນເຄື່ອງ ແລະ ປິດລາຍການ",
        detail: "ລະບົບຄິດຄ່າຝາກຕາມຂັ້ນວັນ; ຮັບເງິນ/ອອກໃບຮັບເງິນ ຕາມລະບຽບ.",
        control: "ຜູ້ຮັບຄືນຕ້ອງເປັນຜູ້ຝາກ ຫຼື ຜູ້ໄດ້ຮັບມອບໝາຍເປັນລາຍລັກອັກສອນ",
      },
      {
        no: 5,
        role: "manager",
        action: "ທົບທວນອັດຕາຄ່າຝາກ",
        screen: { label: "ຕັ້ງຄ່າ ຄ່າຝາກເຄື່ອງ", href: "/settings/deposit" },
      },
    ],
    exceptions: [
      { case: "ຝາກເກີນກຳນົດດົນ", action: "ແຈ້ງເປັນລາຍລັກອັກສອນ ແລະ ສົ່ງເລື່ອງໃຫ້ຜູ້ຈັດການຕັດສິນ." },
      { case: "ຜູ້ຮັບຄືນບໍ່ແມ່ນຜູ້ຝາກ", action: "ຕ້ອງມີໜັງສືມອບສິດ + ບັດປະຈຳຕົວ ຈຶ່ງຄືນໄດ້." },
      { case: "ຍົກເລີກລາຍການ", action: "ສະເພາະຜູ້ຈັດການ ພ້ອມລະບຸເຫດຜົນ." },
    ],
    outputs: ["ລາຍການຝາກທີ່ຕິດຕາມໄດ້", "ຄ່າຝາກທີ່ຄິດຖືກຕ້ອງ"],
    sops: ["SOP-WH-09"],
    wis: ["WI-DEP-01"],
    forms: ["F-19"],
    kpis: [{ name: "ລາຍການຝາກເກີນກຳນົດ", target: "≤ 5%" }],
  },
  {
    code: "WF-10",
    name: "ຄວບຄຸມລະດັບ stock ແລະ ລາຍງານ",
    tone: "emerald",
    goal: "ບໍ່ຂາດຂອງຂາຍ ແລະ ບໍ່ຄ້າງທຶນຈົມ — ດ້ວຍການເຝົ້າລະດັບ stock ແລະ ລາຍງານປະຈຳ.",
    trigger: "ປະຈຳວັນ (badge + ລາຍງານທາງເມວ) ແລະ ປະຈຳເດືອນ (ທົບທວນຄ່າ).",
    scope: "ສາງທີ່ເປີດການຄຸມ stock ຂັ້ນຕ່ຳ/ຂັ້ນສູງ ແລະ ລາຍງານບໍລິຫານທັງໝົດ.",
    owner: "manager",
    roles: ["manager", "supervisor", "purchasing"],
    steps: [
      {
        no: 1,
        role: "manager",
        action: "ເປີດການຄຸມຕໍ່ສາງ ແລະ ຕັ້ງຄ່າ min/max",
        detail: "ຕັ້ງເປັນລາຍການ ຫຼື ນຳເຂົ້າ Excel (ດາວໂຫຼດ template ທີ່ມີຄ່າປັດຈຸບັນ).",
        screen: { label: "ຕັ້ງຄ່າ stock ຂັ້ນຕ່ຳ/ຂັ້ນສູງ", href: "/settings/min-stock" },
        form: "F-21",
      },
      {
        no: 2,
        role: "supervisor",
        action: "ກວດ badge ສຸຂະພາບປະຈຳວັນ",
        detail: "ຕ່ຳກວ່າຂັ້ນຕ່ຳ · ສິນຄ້າຄ້າງ · SN ບໍ່ຕົງ.",
        screen: { label: "ໜ້າຫຼັກ", href: "/" },
      },
      {
        no: 3,
        role: "purchasing",
        action: "ສັ່ງເຕີມລາຍການທີ່ຕ່ຳກວ່າຂັ້ນຕ່ຳ",
        screen: { label: "stock ຂັ້ນຕ່ຳ / ຂັ້ນສູງ", href: "/movements/min-stock" },
      },
      {
        no: 4,
        role: "manager",
        action: "ທົບທວນ Aging ແລະ Movers",
        detail: "ສິນຄ້າຄ້າງດົນ → ຈັດໂປຣໂມຊັນ/ຄືນຜູ້ສະໜອງ; fast movers → ຈັດໄວ້ບ່ອນເກັບໃກ້ທາງອອກ.",
        screen: { label: "ສິນຄ້າຄ້າງ (Aging)", href: "/movements/aging" },
      },
      {
        no: 5,
        role: "manager",
        action: "ຕັ້ງລາຍງານທາງເມວ ແລະ ອ່ານທຸກເຊົ້າ",
        screen: { label: "ລາຍງານທາງເມວ", href: "/settings/email-reports" },
        form: "F-22",
      },
    ],
    exceptions: [
      { case: "ບໍ່ມີສາງໃດເປີດຄຸມ", action: "ຈະບໍ່ມີການເຕືອນເລີຍ — ຜູ້ຈັດການຕ້ອງເປີດສາງໃນໜ້າຕັ້ງຄ່າກ່ອນ." },
      { case: "ຄ່າ min/max ບໍ່ຕົງກັບຄວາມຈິງ", action: "ທົບທວນຢ່າງໜ້ອຍໄຕມາດລະຄັ້ງ ຫຼື ເມື່ອຮູບແບບການຂາຍປ່ຽນ." },
      { case: "ເມວບໍ່ອອກ", action: "ແຈ້ງໄອທີ ກວດການຕັ້ງຄ່າຜູ້ຮັບ ແລະ ຕາຕະລາງສົ່ງ." },
    ],
    outputs: ["ລາຍການສັ່ງເຕີມ", "ລາຍງານປະຈຳວັນ/ອາທິດ", "ການຕັດສິນໃຈຈັດການສິນຄ້າຄ້າງ"],
    sops: ["SOP-WH-10"],
    wis: ["WI-SET-02", "WI-RPT-01", "WI-RPT-02", "WI-RPT-03", "WI-RPT-04", "WI-RPT-05"],
    forms: ["F-21", "F-22", "F-23", "F-25"],
    kpis: [
      { name: "ລາຍການຂາດ stock", target: "≤ 5 ລາຍການ" },
      { name: "ສິນຄ້າຄ້າງເກີນ 90 ມື້", target: "ຫຼຸດລົງທຸກໄຕມາດ" },
    ],
  },
  {
    code: "WF-11",
    name: "ຈັດການສິດ ແລະ ຕັ້ງຄ່າລະບົບ",
    tone: "navy",
    goal: "ຄົນທີ່ຖືກຕ້ອງເທົ່ານັ້ນ ເຂົ້າເຖິງສາງທີ່ຖືກຕ້ອງ ແລະ ຄ່າຕັ້ງລະບົບສະທ້ອນວິທີເຮັດວຽກຈິງ.",
    trigger: "ພະນັກງານເຂົ້າໃໝ່/ຍ້າຍ/ລາອອກ ຫຼື ມີການປ່ຽນແປງໂຄງສ້າງສາງ.",
    scope: "ສິດເຂົ້າເຖິງ, ສາງ/rack/location, ການເກັບ ISN, ຍີ່ຫໍ້ບັງຄັບ SN, ຄ່າຝາກ, ລາຍງານທາງເມວ.",
    owner: "manager",
    roles: ["manager", "it", "supervisor"],
    steps: [
      {
        no: 1,
        role: "supervisor",
        action: "ສົ່ງຄຳຂໍເປີດ/ປິດສິດ ພ້ອມລະບຸສາງ ແລະ ລະດັບ",
      },
      {
        no: 2,
        role: "manager",
        action: "ກຳນົດ role ແລະ ສາງທີ່ຮັບຜິດຊອບ",
        detail: "ຜູ້ຈັດການ = ທຸກສາງ (ຫຼື ຈຳກັດເອງ); Supervisor/ນາຍສາງ = ສະເພາະສາງທີ່ມອບໝາຍ.",
        screen: { label: "ຈັດການສິດເຂົ້າເຖິງ", href: "/settings/access" },
        control: "ໃຫ້ສິດເທົ່າທີ່ຈຳເປັນ (least privilege)",
      },
      {
        no: 3,
        role: "manager",
        action: "ຕັ້ງຄ່າສາງ / rack / location ແລະ ການໃຊ້ SN ຕໍ່ເມນູ",
        screen: { label: "ສາງ / Rack / Location", href: "/settings/warehouses" },
      },
      {
        no: 4,
        role: "manager",
        action: "ກຳນົດຂອບເຂດສິນຄ້າທີ່ຕ້ອງເກັບ ISN",
        detail: "ຄຸມດ້ວຍໝວດ + ລາຍການຍົກເວັ້ນ ແລະ ຍີ່ຫໍ້ທີ່ບັງຄັບ SN+ISN.",
        screen: { label: "ສິນຄ້າທີ່ຕ້ອງເກັບ ISN", href: "/settings/isn-scope" },
      },
      {
        no: 5,
        role: "it",
        action: "ນຳໃຊ້ migration ແລະ ດູແລລະບົບ",
        detail: "ຂໍ້ຄວາມຜິດພາດແບບ column does not exist ໝາຍເຖິງ migration ຄ້າງ ບໍ່ແມ່ນຂໍ້ມູນຜິດ.",
      },
      {
        no: 6,
        role: "manager",
        action: "ທົບທວນສິດປະຈຳເດືອນ",
        detail: "ຄົນອອກ/ຍ້າຍພະແນກ ຕ້ອງຖອນສິດພາຍໃນມື້ດຽວກັນ.",
        screen: { label: "ຈັດການສິດເຂົ້າເຖິງ", href: "/settings/access" },
      },
    ],
    exceptions: [
      { case: "ຜູ້ໃຊ້ບໍ່ເຫັນສາງຂອງຕົນ", action: "ກວດວ່າມີການມອບໝາຍສາງໃນໜ້າຈັດການສິດແລ້ວບໍ." },
      { case: "ຄົນລາອອກ", action: "ຖອນສິດທັນທີ ແລະ ໂອນວຽກຄ້າງໃຫ້ຜູ້ອື່ນ." },
      { case: "ໜ້າຈໍຂຶ້ນ error 500", action: "ແຈ້ງໄອທີ ພ້ອມຊື່ໜ້າ ແລະ ສິ່ງທີ່ກົດ — ສ່ວນຫຼາຍແມ່ນ migration ຄ້າງ." },
    ],
    outputs: ["ທະບຽນສິດເຂົ້າເຖິງທີ່ເປັນປັດຈຸບັນ", "ຄ່າຕັ້ງລະບົບທີ່ຖືກຕ້ອງ"],
    sops: ["SOP-WH-11"],
    wis: ["WI-SET-01", "WI-SET-03", "WI-SET-04", "WI-SET-05"],
    forms: [],
    kpis: [
      { name: "ຖອນສິດພາຍໃນມື້ທີ່ລາອອກ", target: "100%" },
      { name: "ບັນຊີທີ່ບໍ່ໄດ້ໃຊ້ເກີນ 90 ມື້", target: "0" },
    ],
  },
];

export const WORKFLOW_BY_CODE = new Map(WORKFLOWS.map((w) => [w.code, w]));
